table di_citing_organization
	lineageTag: fb30366f-2408-4cba-8e40-31603d62ac93

	column grid_id
		dataType: string
		lineageTag: 449cef22-2727-4c9a-900d-1c9b0e94fcba
		summarizeBy: none
		sourceColumn: grid_id

		annotation SummarizationSetBy = Automatic

	column org_name
		dataType: string
		lineageTag: d458a408-0726-44a2-a313-c81605d7e400
		summarizeBy: none
		sourceColumn: org_name

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: 49a3545e-f2e0-4dd8-b962-a7ae0cd41fe7
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column is_gsk
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cde94c60-a2d9-42ea-b9fd-ff303d25462e
		summarizeBy: none
		sourceColumn: is_gsk

		annotation SummarizationSetBy = Automatic

	column citing_via_publication_count
		dataType: int64
		formatString: 0
		lineageTag: 9417ef54-05c7-4f00-b782-e89f10319a31
		summarizeBy: sum
		sourceColumn: citing_via_publication_count

		annotation SummarizationSetBy = Automatic

	column citing_via_clinical_trial_count
		dataType: int64
		formatString: 0
		lineageTag: 0d418da4-7a95-47f2-ba6f-e466541ff1ae
		summarizeBy: sum
		sourceColumn: citing_via_clinical_trial_count

		annotation SummarizationSetBy = Automatic

	column total_citing_count
		dataType: int64
		formatString: 0
		lineageTag: c6e13db0-5510-4605-b350-6d80dda3f253
		summarizeBy: sum
		sourceColumn: total_citing_count

		annotation SummarizationSetBy = Automatic

	column avg_field_citation_ratio
		dataType: double
		lineageTag: e960baff-5c9f-4fc8-b954-f96575955239
		summarizeBy: sum
		sourceColumn: avg_field_citation_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_altmetric_score
		dataType: string
		lineageTag: 0e47b579-412e-47f0-a840-bf2651726d6c
		summarizeBy: none
		sourceColumn: avg_altmetric_score

		annotation SummarizationSetBy = Automatic

	column org_rank
		dataType: int64
		formatString: 0
		lineageTag: 6220acf1-145c-4a71-8be1-f3ffdbce5ab2
		summarizeBy: sum
		sourceColumn: org_rank

		annotation SummarizationSetBy = Automatic

	partition di_citing_organization = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    di_citing_organization_Sheet = Source{[Item="di_citing_organization",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(di_citing_organization_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"grid_id", type text}, {"org_name", type text}, {"country_name", type text}, {"is_gsk", type logical}, {"citing_via_publication_count", Int64.Type}, {"citing_via_clinical_trial_count", Int64.Type}, {"total_citing_count", Int64.Type}, {"avg_field_citation_ratio", type number}, {"avg_altmetric_score", type any}, {"org_rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

