table document_impact_geography
	lineageTag: 3982af0e-c36c-4282-b911-9502e60ec7f1

	column doi
		dataType: string
		lineageTag: be36f943-1430-4b68-9b2e-95bb91de4447
		summarizeBy: none
		sourceColumn: doi

		annotation SummarizationSetBy = Automatic

	column platform
		dataType: string
		lineageTag: 8ce3f761-6471-4967-8ce9-df609c94eee1
		summarizeBy: none
		sourceColumn: platform

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: 3fcb0db5-75d7-43fd-a604-c1c149989f71
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column mention_count
		dataType: int64
		formatString: 0
		lineageTag: 701e4e71-e2b8-4625-9fa6-f2f54ff2f218
		summarizeBy: sum
		sourceColumn: mention_count

		annotation SummarizationSetBy = Automatic

	column sample_note
		dataType: string
		lineageTag: abf4ea35-044f-41c3-9f16-6319f6f0bcd2
		summarizeBy: none
		sourceColumn: sample_note

		annotation SummarizationSetBy = Automatic

	partition document_impact_geography = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    document_impact_geography_Sheet = Source{[Item="document_impact_geography",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(document_impact_geography_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"doi", type text}, {"platform", type text}, {"country_code", type text}, {"mention_count", Int64.Type}, {"sample_note", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

