table document_impact_clinical_trial
	lineageTag: 53337d5a-9b1e-41a3-8c76-7a7aced349a3

	column dimensions_id
		dataType: string
		lineageTag: 9b6a4666-5422-4f6b-b3b8-9fabdd7e13d8
		summarizeBy: none
		sourceColumn: dimensions_id

		annotation SummarizationSetBy = Automatic

	column doi
		dataType: string
		lineageTag: a479b0a7-c3fc-48ec-855f-44f9c647d5f8
		summarizeBy: none
		sourceColumn: doi

		annotation SummarizationSetBy = Automatic

	column ct_id
		dataType: string
		lineageTag: 4a30bf2a-4676-4f2c-b1b0-6b784b0981d0
		summarizeBy: none
		sourceColumn: ct_id

		annotation SummarizationSetBy = Automatic

	partition document_impact_clinical_trial = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    document_impact_clinical_trial_Sheet = Source{[Item="document_impact_clinical_trial",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(document_impact_clinical_trial_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"dimensions_id", type any}, {"doi", type any}, {"ct_id", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

