table document_impact_funder
	lineageTag: c334ce77-ec12-466c-9ece-e7b00c6f5b4e

	column source_dimensions_id
		dataType: string
		lineageTag: ba7627fe-bacc-4007-beb4-c04bf9167549
		summarizeBy: none
		sourceColumn: source_dimensions_id

		annotation SummarizationSetBy = Automatic

	column org_grid_id
		dataType: string
		lineageTag: 316104f6-22b8-402a-b745-6199fbdcff97
		summarizeBy: none
		sourceColumn: org_grid_id

		annotation SummarizationSetBy = Automatic

	column org_name
		dataType: string
		lineageTag: 1637fe7b-c39d-402d-8dea-40724ade6ade
		summarizeBy: none
		sourceColumn: org_name

		annotation SummarizationSetBy = Automatic

	column acronyms
		dataType: string
		lineageTag: 3ac7dda3-958c-47a6-9338-d6efd49adb7d
		summarizeBy: none
		sourceColumn: acronyms

		annotation SummarizationSetBy = Automatic

	column city_name
		dataType: string
		lineageTag: 1080b538-b6d4-4564-8c99-c4bef37e3996
		summarizeBy: none
		sourceColumn: city_name

		annotation SummarizationSetBy = Automatic

	column cnrs_ids
		dataType: string
		lineageTag: 0e6117fb-9060-4a5c-a8e9-b1300f1bc196
		summarizeBy: none
		sourceColumn: cnrs_ids

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: 50f0825c-ae17-45e9-93ad-397430a1c377
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: 282bd01d-7528-409b-8812-2cebc544940d
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 3a8adc08-35df-4fbc-bf09-8b40f577c44e
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column established
		dataType: string
		lineageTag: 85724d77-7d86-4f2d-850d-98ec9e790f9c
		summarizeBy: none
		sourceColumn: established

		annotation SummarizationSetBy = Automatic

	column external_ids_fundref
		dataType: string
		lineageTag: fe5846d2-b868-41aa-a60f-447034fadf8e
		summarizeBy: none
		sourceColumn: external_ids_fundref

		annotation SummarizationSetBy = Automatic

	column hesa_ids
		dataType: string
		lineageTag: d54612bd-58aa-40e8-854a-28de53e21a1a
		summarizeBy: none
		sourceColumn: hesa_ids

		annotation SummarizationSetBy = Automatic

	column hierarchy_details
		dataType: string
		lineageTag: cd80b73a-585f-4ff0-a03c-b59ff7492284
		summarizeBy: none
		sourceColumn: hierarchy_details

		annotation SummarizationSetBy = Automatic

	column isni_ids
		dataType: string
		lineageTag: 9ad01947-0f31-480f-b3b4-2948a032277f
		summarizeBy: none
		sourceColumn: isni_ids

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 70f043e9-0317-4b31-a84e-1db9ac771ea7
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column linkout
		dataType: string
		lineageTag: e97d2bfc-90f2-421b-8218-7bcee33572cd
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		lineageTag: 1060eefc-f762-49e5-b526-6ce49611e4c2
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nuts_level1_code
		dataType: string
		lineageTag: 47aa6206-4974-4281-8538-d8704f0968b9
		summarizeBy: none
		sourceColumn: nuts_level1_code

		annotation SummarizationSetBy = Automatic

	column nuts_level1_name
		dataType: string
		lineageTag: 11647bab-f3bb-4998-8858-e418832e0925
		summarizeBy: none
		sourceColumn: nuts_level1_name

		annotation SummarizationSetBy = Automatic

	column nuts_level2_code
		dataType: string
		lineageTag: 314baecd-39da-4f9b-a488-cf38f15887a4
		summarizeBy: none
		sourceColumn: nuts_level2_code

		annotation SummarizationSetBy = Automatic

	column nuts_level2_name
		dataType: string
		lineageTag: faa98cc3-103d-436a-beec-f1faaff26319
		summarizeBy: none
		sourceColumn: nuts_level2_name

		annotation SummarizationSetBy = Automatic

	column nuts_level3_code
		dataType: string
		lineageTag: 64caf55a-55d0-434e-b247-4f2180876aa1
		summarizeBy: none
		sourceColumn: nuts_level3_code

		annotation SummarizationSetBy = Automatic

	column nuts_level3_name
		dataType: string
		lineageTag: 0f4f416e-df06-41ee-b465-acb72684f8b8
		summarizeBy: none
		sourceColumn: nuts_level3_name

		annotation SummarizationSetBy = Automatic

	column organization_child_ids
		dataType: string
		lineageTag: 21158318-b794-4c02-8754-710cdd070f0d
		summarizeBy: none
		sourceColumn: organization_child_ids

		annotation SummarizationSetBy = Automatic

	column organization_parent_ids
		dataType: string
		lineageTag: fa7a91d1-d6cd-4932-9ec1-d030dd228ea1
		summarizeBy: none
		sourceColumn: organization_parent_ids

		annotation SummarizationSetBy = Automatic

	column organization_related_ids
		dataType: string
		lineageTag: 7b604da1-871f-4c5a-b0ea-87d6b0ab12ce
		summarizeBy: none
		sourceColumn: organization_related_ids

		annotation SummarizationSetBy = Automatic

	column orgref_ids
		dataType: string
		lineageTag: be66b8c5-9924-40c4-9c04-339ab0d5a553
		summarizeBy: none
		sourceColumn: orgref_ids

		annotation SummarizationSetBy = Automatic

	column redirect
		dataType: string
		lineageTag: dcc424c8-7431-4675-9138-c118b4c3b2b7
		summarizeBy: none
		sourceColumn: redirect

		annotation SummarizationSetBy = Automatic

	column ror_ids
		dataType: string
		lineageTag: 2805d72d-26d7-4169-aecc-e46854f013d6
		summarizeBy: none
		sourceColumn: ror_ids

		annotation SummarizationSetBy = Automatic

	column state_name
		dataType: string
		lineageTag: d947476a-6cdf-4c3a-805c-5753a846e983
		summarizeBy: none
		sourceColumn: state_name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 9bef64fe-1e4a-4d00-a496-22461243f804
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column types
		dataType: string
		lineageTag: ac925086-cc11-4af8-8c77-0e9933ea31f8
		summarizeBy: none
		sourceColumn: types

		annotation SummarizationSetBy = Automatic

	column ucas_ids
		dataType: string
		lineageTag: 7ee5e313-2e4b-4e88-a414-f395c07b2348
		summarizeBy: none
		sourceColumn: ucas_ids

		annotation SummarizationSetBy = Automatic

	column ukprn_ids
		dataType: string
		lineageTag: 703246c8-643c-484b-82ba-a320c6e6b59d
		summarizeBy: none
		sourceColumn: ukprn_ids

		annotation SummarizationSetBy = Automatic

	column ultimate_parent_id
		dataType: string
		lineageTag: 13ed4543-fbd8-4db8-8726-7ec5effc7432
		summarizeBy: none
		sourceColumn: ultimate_parent_id

		annotation SummarizationSetBy = Automatic

	column wikidata_ids
		dataType: string
		lineageTag: f687a7d7-a438-4347-a601-1966188d654a
		summarizeBy: none
		sourceColumn: wikidata_ids

		annotation SummarizationSetBy = Automatic

	column wikipedia_url
		dataType: string
		lineageTag: 305419fc-d0f3-4502-81cc-e592ba677c4f
		summarizeBy: none
		sourceColumn: wikipedia_url

		annotation SummarizationSetBy = Automatic

	partition document_impact_funder = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    document_impact_funder_Sheet = Source{[Item="document_impact_funder",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(document_impact_funder_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_dimensions_id", type text}, {"org_grid_id", type text}, {"org_name", type text}, {"acronyms", type text}, {"city_name", type text}, {"cnrs_ids", type any}, {"country_code", type text}, {"country_name", type text}, {"dimensions_url", type any}, {"established", type any}, {"external_ids_fundref", type any}, {"hesa_ids", type any}, {"hierarchy_details", type any}, {"isni_ids", type any}, {"latitude", type number}, {"linkout", type text}, {"longitude", type number}, {"nuts_level1_code", type any}, {"nuts_level1_name", type any}, {"nuts_level2_code", type any}, {"nuts_level2_name", type any}, {"nuts_level3_code", type any}, {"nuts_level3_name", type any}, {"organization_child_ids", type any}, {"organization_parent_ids", type any}, {"organization_related_ids", type any}, {"orgref_ids", type any}, {"redirect", type any}, {"ror_ids", type any}, {"state_name", type text}, {"status", type any}, {"types", type text}, {"ucas_ids", type any}, {"ukprn_ids", type any}, {"ultimate_parent_id", type any}, {"wikidata_ids", type any}, {"wikipedia_url", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

