table document_impact_researcher
	lineageTag: a38bffec-5ee6-4817-b574-01c5caad2b79

	column source_dimensions_id
		dataType: string
		lineageTag: b238e271-2013-4197-82c5-e75c0d4e77ec
		summarizeBy: none
		sourceColumn: source_dimensions_id

		annotation SummarizationSetBy = Automatic

	column researcher_id
		dataType: string
		lineageTag: e4ae3032-a8c9-4701-8e44-50a9abda9604
		summarizeBy: none
		sourceColumn: researcher_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 806d6f15-abb5-463a-904c-5b2fd371c38e
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 33239898-8a31-49bd-9c96-bfefaa20fff5
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column orcid_id
		dataType: string
		lineageTag: 3980fd0e-c943-44a5-abde-890a0845ac9d
		summarizeBy: none
		sourceColumn: orcid_id

		annotation SummarizationSetBy = Automatic

	column current_research_org
		dataType: string
		lineageTag: 4900009a-70bc-4dde-8f44-402a1604761a
		summarizeBy: none
		sourceColumn: current_research_org

		annotation SummarizationSetBy = Automatic

	column research_orgs
		dataType: string
		lineageTag: f08c7603-e6ed-4363-870a-b25bb3ebe4da
		summarizeBy: none
		sourceColumn: research_orgs

		annotation SummarizationSetBy = Automatic

	column first_grant_year
		dataType: int64
		formatString: 0
		lineageTag: ad040c31-1bf3-4b8d-86d1-b4af4866659c
		summarizeBy: sum
		sourceColumn: first_grant_year

		annotation SummarizationSetBy = Automatic

	column last_grant_year
		dataType: int64
		formatString: 0
		lineageTag: cdd85201-04dd-4118-aebe-95f82da44bde
		summarizeBy: sum
		sourceColumn: last_grant_year

		annotation SummarizationSetBy = Automatic

	column first_publication_year
		dataType: int64
		formatString: 0
		lineageTag: 2a28cb24-42f7-4c25-8aa6-3530b4c62991
		summarizeBy: sum
		sourceColumn: first_publication_year

		annotation SummarizationSetBy = Automatic

	column last_publication_year
		dataType: int64
		formatString: 0
		lineageTag: 4985e460-eda3-4c5b-826b-22ea636a5861
		summarizeBy: sum
		sourceColumn: last_publication_year

		annotation SummarizationSetBy = Automatic

	column total_grants
		dataType: int64
		formatString: 0
		lineageTag: fa638c0b-212c-4f59-a10a-5b476209ef97
		summarizeBy: sum
		sourceColumn: total_grants

		annotation SummarizationSetBy = Automatic

	column total_publications
		dataType: int64
		formatString: 0
		lineageTag: c793fc66-4630-45dd-ae2b-04f31e8e56b7
		summarizeBy: sum
		sourceColumn: total_publications

		annotation SummarizationSetBy = Automatic

	column nih_ppid
		dataType: int64
		formatString: 0
		lineageTag: 66263d1a-2dc8-41f1-8aeb-89e14812376a
		summarizeBy: sum
		sourceColumn: nih_ppid

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 0626915c-b8d3-438c-afc2-3f2a46ea8efa
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column obsolete
		dataType: int64
		formatString: 0
		lineageTag: 45b65618-d331-4f98-ae06-d3e78e599ee7
		summarizeBy: sum
		sourceColumn: obsolete

		annotation SummarizationSetBy = Automatic

	column redirect
		dataType: string
		lineageTag: c0b596b2-78ff-40a4-b11c-f0e418b194de
		summarizeBy: none
		sourceColumn: redirect

		annotation SummarizationSetBy = Automatic

	column relevance_score
		dataType: string
		lineageTag: d9c86c04-f739-4e2f-aeb3-44ad6528bbdc
		summarizeBy: none
		sourceColumn: relevance_score

		annotation SummarizationSetBy = Automatic

	partition document_impact_researcher = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    document_impact_researcher_Sheet = Source{[Item="document_impact_researcher",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(document_impact_researcher_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_dimensions_id", type text}, {"researcher_id", type text}, {"first_name", type text}, {"last_name", type text}, {"orcid_id", type text}, {"current_research_org", type text}, {"research_orgs", type text}, {"first_grant_year", Int64.Type}, {"last_grant_year", Int64.Type}, {"first_publication_year", Int64.Type}, {"last_publication_year", Int64.Type}, {"total_grants", Int64.Type}, {"total_publications", Int64.Type}, {"nih_ppid", Int64.Type}, {"dimensions_url", type text}, {"obsolete", Int64.Type}, {"redirect", type text}, {"relevance_score", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

