table enr_pub_citing_publication
	lineageTag: a7f5d882-a08f-4c4e-a3cc-015544c14ba9

	column citing_dimensions_id
		dataType: string
		lineageTag: c7911395-5686-4225-9806-360fd41a8f8f
		summarizeBy: none
		sourceColumn: citing_dimensions_id

		annotation SummarizationSetBy = Automatic

	column citing_doi
		dataType: string
		lineageTag: b93de6a9-c1c5-4c7f-acc9-a9c7986cfc0f
		summarizeBy: none
		sourceColumn: citing_doi

		annotation SummarizationSetBy = Automatic

	column journal_id
		dataType: string
		lineageTag: 10a064fc-4c0f-4561-889b-502fbd0c0e67
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column journal_title
		dataType: string
		lineageTag: 07696f1c-1807-4429-8f01-84d9ab92fb45
		summarizeBy: none
		sourceColumn: journal_title

		annotation SummarizationSetBy = Automatic

	column pub_year
		dataType: int64
		formatString: 0
		lineageTag: 804cea5f-0d3c-484e-a770-336d1ea67a83
		summarizeBy: sum
		sourceColumn: pub_year

		annotation SummarizationSetBy = Automatic

	column document_type
		dataType: string
		lineageTag: e53f7bc8-6e51-485c-9fb7-2ffa6327829e
		summarizeBy: none
		sourceColumn: document_type

		annotation SummarizationSetBy = Automatic

	column times_cited
		dataType: int64
		formatString: 0
		lineageTag: 47c648b9-d88e-46de-8b6a-1b42bf48add4
		summarizeBy: sum
		sourceColumn: times_cited

		annotation SummarizationSetBy = Automatic

	column field_citation_ratio
		dataType: string
		lineageTag: e1385933-f9fc-48d1-9a01-5d55ac240974
		summarizeBy: none
		sourceColumn: field_citation_ratio

		annotation SummarizationSetBy = Automatic

	column altmetric_score_citing
		dataType: string
		lineageTag: 3dade60d-51dc-4ed1-ab2c-ee0fe3fb30fd
		summarizeBy: none
		sourceColumn: altmetric_score_citing

		annotation SummarizationSetBy = Automatic

	column enr_loaded_at
		dataType: string
		lineageTag: f257679e-8172-49fd-b5db-101f98d48927
		summarizeBy: none
		sourceColumn: enr_loaded_at

		annotation SummarizationSetBy = Automatic

	partition enr_pub_citing_publication = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    enr_pub_citing_publication_Sheet = Source{[Item="enr_pub_citing_publication",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(enr_pub_citing_publication_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"citing_dimensions_id", type text}, {"citing_doi", type text}, {"journal_id", type text}, {"journal_title", type text}, {"pub_year", Int64.Type}, {"document_type", type text}, {"times_cited", Int64.Type}, {"field_citation_ratio", type any}, {"altmetric_score_citing", type any}, {"enr_loaded_at", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

