table enr_pub_citing_pub_org
	lineageTag: e309fc26-e04d-40d5-81cf-e42371f2927e

	column citing_dimensions_id
		dataType: string
		lineageTag: d5653ca5-3713-41bb-ad45-df785556f44c
		summarizeBy: none
		sourceColumn: citing_dimensions_id

		annotation SummarizationSetBy = Automatic

	column grid_id
		dataType: string
		lineageTag: 44b0843a-8055-468f-807d-09683de03d06
		summarizeBy: none
		sourceColumn: grid_id

		annotation SummarizationSetBy = Automatic

	column org_name
		dataType: string
		lineageTag: eba3cdfe-9fe1-4aac-9b1a-516ad72c5bac
		summarizeBy: none
		sourceColumn: org_name

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: a5f67d90-fabf-4566-9751-94dc88b1309e
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: 16a97628-3427-4c48-9856-68b5e5f395f6
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column enr_loaded_at
		dataType: string
		lineageTag: 39b6dace-13f7-4503-b825-17b2b27ff7f7
		summarizeBy: none
		sourceColumn: enr_loaded_at

		annotation SummarizationSetBy = Automatic

	partition enr_pub_citing_pub_org = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    enr_pub_citing_pub_org_Sheet = Source{[Item="enr_pub_citing_pub_org",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(enr_pub_citing_pub_org_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"citing_dimensions_id", type text}, {"grid_id", type text}, {"org_name", type text}, {"country_name", type text}, {"country_code", type text}, {"enr_loaded_at", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

