table enr_funder
	lineageTag: 73086440-3a1f-4b8c-9902-c5bee4848b98

	column source_dimensions_id
		dataType: string
		lineageTag: c5724c1b-f8fb-42d8-aa84-8e93a9d5a411
		summarizeBy: none
		sourceColumn: source_dimensions_id

		annotation SummarizationSetBy = Automatic

	column org_grid_id
		dataType: string
		lineageTag: 088de6ff-88b4-4c4a-b583-02ee2febddbc
		summarizeBy: none
		sourceColumn: org_grid_id

		annotation SummarizationSetBy = Automatic

	column org_name
		dataType: string
		lineageTag: 5304d5c7-aee4-4bc2-867a-3622b405c39d
		summarizeBy: none
		sourceColumn: org_name

		annotation SummarizationSetBy = Automatic

	column acronyms
		dataType: string
		lineageTag: 68280966-28d3-4d60-bd8a-cd3bf5198e21
		summarizeBy: none
		sourceColumn: acronyms

		annotation SummarizationSetBy = Automatic

	column city_name
		dataType: string
		lineageTag: ca33cef8-1745-4645-a812-dedf531de9be
		summarizeBy: none
		sourceColumn: city_name

		annotation SummarizationSetBy = Automatic

	column cnrs_ids
		dataType: string
		lineageTag: 028bfef9-f237-4320-af8e-f8fb297dbce0
		summarizeBy: none
		sourceColumn: cnrs_ids

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: 8d9e5327-2c6c-415c-b17e-7a5795f7b5f0
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: 38cf345f-bdae-401b-9bd7-0b34a9397b88
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 5c29e87e-c830-4964-bc48-5191be27f140
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column established
		dataType: string
		lineageTag: f8d2c716-1031-4598-b9a2-af5054d2daf1
		summarizeBy: none
		sourceColumn: established

		annotation SummarizationSetBy = Automatic

	column external_ids_fundref
		dataType: string
		lineageTag: c868e3bd-3ab8-4d54-a069-be417d571234
		summarizeBy: none
		sourceColumn: external_ids_fundref

		annotation SummarizationSetBy = Automatic

	column hesa_ids
		dataType: string
		lineageTag: 30d09a72-9cb7-436a-9b95-727fc366dff1
		summarizeBy: none
		sourceColumn: hesa_ids

		annotation SummarizationSetBy = Automatic

	column hierarchy_details
		dataType: string
		lineageTag: 57c306f8-2f69-410f-82da-7d92d5522e8f
		summarizeBy: none
		sourceColumn: hierarchy_details

		annotation SummarizationSetBy = Automatic

	column isni_ids
		dataType: string
		lineageTag: 020f2698-9080-4781-9ff6-4ab1743d4cf5
		summarizeBy: none
		sourceColumn: isni_ids

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 25105c88-3a7b-4290-aad5-ec2192a4a874
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column linkout
		dataType: string
		lineageTag: 606151ef-de1d-434c-a40b-638ad4ab21de
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		lineageTag: 0d9bf23b-660a-46c8-8b17-f0db4d13c7f2
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nuts_level1_code
		dataType: string
		lineageTag: cb8c87be-9783-435e-980f-fabf28a9f4d9
		summarizeBy: none
		sourceColumn: nuts_level1_code

		annotation SummarizationSetBy = Automatic

	column nuts_level1_name
		dataType: string
		lineageTag: 1456c562-1f75-4527-aad7-761d25ecf28a
		summarizeBy: none
		sourceColumn: nuts_level1_name

		annotation SummarizationSetBy = Automatic

	column nuts_level2_code
		dataType: string
		lineageTag: 5086a95c-611f-4800-a90e-783031d1e407
		summarizeBy: none
		sourceColumn: nuts_level2_code

		annotation SummarizationSetBy = Automatic

	column nuts_level2_name
		dataType: string
		lineageTag: 15b29b9c-1bc2-4a8a-af78-1c429d9dcab4
		summarizeBy: none
		sourceColumn: nuts_level2_name

		annotation SummarizationSetBy = Automatic

	column nuts_level3_code
		dataType: string
		lineageTag: 83c1f946-d425-4c9f-8ddc-3f955a6f5878
		summarizeBy: none
		sourceColumn: nuts_level3_code

		annotation SummarizationSetBy = Automatic

	column nuts_level3_name
		dataType: string
		lineageTag: a3491273-4613-424b-a9d0-4a01a0ce952e
		summarizeBy: none
		sourceColumn: nuts_level3_name

		annotation SummarizationSetBy = Automatic

	column organization_child_ids
		dataType: string
		lineageTag: 03310d64-27e2-40c6-aca4-0776b57e955c
		summarizeBy: none
		sourceColumn: organization_child_ids

		annotation SummarizationSetBy = Automatic

	column organization_parent_ids
		dataType: string
		lineageTag: c8d02cf5-00a0-4d61-8575-ea28ac8884c8
		summarizeBy: none
		sourceColumn: organization_parent_ids

		annotation SummarizationSetBy = Automatic

	column organization_related_ids
		dataType: string
		lineageTag: 0592dca5-826b-4c47-87c1-e95b776c97ed
		summarizeBy: none
		sourceColumn: organization_related_ids

		annotation SummarizationSetBy = Automatic

	column orgref_ids
		dataType: string
		lineageTag: 52fad33c-b53c-4b7b-abf5-2ca17715a761
		summarizeBy: none
		sourceColumn: orgref_ids

		annotation SummarizationSetBy = Automatic

	column redirect
		dataType: string
		lineageTag: 5ec94579-263c-4832-b6ae-21c1367d1ecb
		summarizeBy: none
		sourceColumn: redirect

		annotation SummarizationSetBy = Automatic

	column ror_ids
		dataType: string
		lineageTag: 10fd7e4b-7c82-4808-a54b-6e74a8effea5
		summarizeBy: none
		sourceColumn: ror_ids

		annotation SummarizationSetBy = Automatic

	column state_name
		dataType: string
		lineageTag: 556062f5-74ef-4bf0-8137-5c8aa8fd979f
		summarizeBy: none
		sourceColumn: state_name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 38ca3225-046a-4a22-b833-a336ff5828ae
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column types
		dataType: string
		lineageTag: 3e7cefa5-7a1a-4ccd-85bf-69355a34d643
		summarizeBy: none
		sourceColumn: types

		annotation SummarizationSetBy = Automatic

	column ucas_ids
		dataType: string
		lineageTag: 8d12d8e1-83dc-45c0-85d5-ad7566854eab
		summarizeBy: none
		sourceColumn: ucas_ids

		annotation SummarizationSetBy = Automatic

	column ukprn_ids
		dataType: string
		lineageTag: cda96002-4f2d-4f75-b1b8-1ddcfe836129
		summarizeBy: none
		sourceColumn: ukprn_ids

		annotation SummarizationSetBy = Automatic

	column ultimate_parent_id
		dataType: string
		lineageTag: 079755b0-8c0d-4b07-bd4a-c4e075ffcf47
		summarizeBy: none
		sourceColumn: ultimate_parent_id

		annotation SummarizationSetBy = Automatic

	column wikidata_ids
		dataType: string
		lineageTag: 08bd15f7-edf8-4e58-8064-fec7f30a9f49
		summarizeBy: none
		sourceColumn: wikidata_ids

		annotation SummarizationSetBy = Automatic

	column wikipedia_url
		dataType: string
		lineageTag: 6a3e1751-a582-4c78-9e4c-c2f17eb686ee
		summarizeBy: none
		sourceColumn: wikipedia_url

		annotation SummarizationSetBy = Automatic

	partition enr_funder = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    enr_funder_Sheet = Source{[Item="enr_funder",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(enr_funder_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_dimensions_id", type text}, {"org_grid_id", type text}, {"org_name", type text}, {"acronyms", type text}, {"city_name", type text}, {"cnrs_ids", type any}, {"country_code", type text}, {"country_name", type text}, {"dimensions_url", type any}, {"established", type any}, {"external_ids_fundref", type any}, {"hesa_ids", type any}, {"hierarchy_details", type any}, {"isni_ids", type any}, {"latitude", type number}, {"linkout", type text}, {"longitude", type number}, {"nuts_level1_code", type any}, {"nuts_level1_name", type any}, {"nuts_level2_code", type any}, {"nuts_level2_name", type any}, {"nuts_level3_code", type any}, {"nuts_level3_name", type any}, {"organization_child_ids", type any}, {"organization_parent_ids", type any}, {"organization_related_ids", type any}, {"orgref_ids", type any}, {"redirect", type any}, {"ror_ids", type any}, {"state_name", type text}, {"status", type any}, {"types", type text}, {"ucas_ids", type any}, {"ukprn_ids", type any}, {"ultimate_parent_id", type any}, {"wikidata_ids", type any}, {"wikipedia_url", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

