table enr_researcher
	lineageTag: c427dce9-9540-4285-8cea-b9fe16cc71b4

	column source_dimensions_id
		dataType: string
		lineageTag: 3d659a95-045b-47d8-a6b0-1a4402045218
		summarizeBy: none
		sourceColumn: source_dimensions_id

		annotation SummarizationSetBy = Automatic

	column researcher_id
		dataType: string
		lineageTag: f740b42b-cdb4-43e6-a821-bbc7a19fd897
		summarizeBy: none
		sourceColumn: researcher_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: e90da874-3d2c-4abe-970d-f249dd04e5f8
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: e0e22b7c-50e8-4aa3-9d64-476fc194284b
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column orcid_id
		dataType: string
		lineageTag: 1fe8c3c4-fd97-4528-bb96-0eb5fd5b7917
		summarizeBy: none
		sourceColumn: orcid_id

		annotation SummarizationSetBy = Automatic

	column current_research_org
		dataType: string
		lineageTag: eda4da13-eb7e-48a2-ac1c-7b4aad498601
		summarizeBy: none
		sourceColumn: current_research_org

		annotation SummarizationSetBy = Automatic

	column research_orgs
		dataType: string
		lineageTag: 95d0d887-0a6e-44a1-9d74-6bc25de69343
		summarizeBy: none
		sourceColumn: research_orgs

		annotation SummarizationSetBy = Automatic

	column first_grant_year
		dataType: int64
		formatString: 0
		lineageTag: dd72c376-daf8-4908-a0bc-667add6f41f7
		summarizeBy: sum
		sourceColumn: first_grant_year

		annotation SummarizationSetBy = Automatic

	column last_grant_year
		dataType: int64
		formatString: 0
		lineageTag: a99ec779-6996-4143-be5b-72317d68f914
		summarizeBy: sum
		sourceColumn: last_grant_year

		annotation SummarizationSetBy = Automatic

	column first_publication_year
		dataType: int64
		formatString: 0
		lineageTag: 55c06a34-d4ac-4561-8d34-8cc86611001a
		summarizeBy: sum
		sourceColumn: first_publication_year

		annotation SummarizationSetBy = Automatic

	column last_publication_year
		dataType: int64
		formatString: 0
		lineageTag: be92407b-93d0-43af-899d-878efdc4cacb
		summarizeBy: sum
		sourceColumn: last_publication_year

		annotation SummarizationSetBy = Automatic

	column total_grants
		dataType: int64
		formatString: 0
		lineageTag: 4ad5d3ac-c6f1-41c2-a4f9-edba81686901
		summarizeBy: sum
		sourceColumn: total_grants

		annotation SummarizationSetBy = Automatic

	column total_publications
		dataType: int64
		formatString: 0
		lineageTag: 25893b87-faf2-4aa6-9d2c-a64c13b245f2
		summarizeBy: sum
		sourceColumn: total_publications

		annotation SummarizationSetBy = Automatic

	column nih_ppid
		dataType: int64
		formatString: 0
		lineageTag: 4a76111d-0d4b-4c48-bb0b-e8f82c637016
		summarizeBy: sum
		sourceColumn: nih_ppid

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 398693f3-abcf-4d0f-9188-f34a49f405e0
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column obsolete
		dataType: int64
		formatString: 0
		lineageTag: 3483ce9b-0f91-448e-956e-323e2f1bfa1b
		summarizeBy: sum
		sourceColumn: obsolete

		annotation SummarizationSetBy = Automatic

	column redirect
		dataType: string
		lineageTag: daa403d1-5be0-4fc5-a42e-9f6b891f0bf2
		summarizeBy: none
		sourceColumn: redirect

		annotation SummarizationSetBy = Automatic

	column relevance_score
		dataType: string
		lineageTag: b3e95fc4-26e0-4efd-99f0-3ffd49b8ee1d
		summarizeBy: none
		sourceColumn: relevance_score

		annotation SummarizationSetBy = Automatic

	partition enr_researcher = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    enr_researcher_Sheet = Source{[Item="enr_researcher",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(enr_researcher_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_dimensions_id", type text}, {"researcher_id", type text}, {"first_name", type text}, {"last_name", type text}, {"orcid_id", type text}, {"current_research_org", type text}, {"research_orgs", type text}, {"first_grant_year", Int64.Type}, {"last_grant_year", Int64.Type}, {"first_publication_year", Int64.Type}, {"last_publication_year", Int64.Type}, {"total_grants", Int64.Type}, {"total_publications", Int64.Type}, {"nih_ppid", Int64.Type}, {"dimensions_url", type text}, {"obsolete", Int64.Type}, {"redirect", type text}, {"relevance_score", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

