table enr_citing_clinical_trial
	lineageTag: 4120ae13-808f-40f0-a5c3-ddf3a9cb1ee5

	column cited_dimensions_id
		dataType: string
		lineageTag: d14172ab-c966-424a-9c88-80ae430756b4
		summarizeBy: none
		sourceColumn: cited_dimensions_id

		annotation SummarizationSetBy = Automatic

	column ct_id
		dataType: string
		lineageTag: 39d9549e-d25b-4c0e-8d04-d3d85f7b4d43
		summarizeBy: none
		sourceColumn: ct_id

		annotation SummarizationSetBy = Automatic

	column abstract
		dataType: string
		lineageTag: 993ae39b-34ee-43d9-9944-f56212195099
		summarizeBy: none
		sourceColumn: abstract

		annotation SummarizationSetBy = Automatic

	column acronym
		dataType: string
		lineageTag: cc5a180a-83a7-49ba-aaf7-d7e4f968f9ed
		summarizeBy: none
		sourceColumn: acronym

		annotation SummarizationSetBy = Automatic

	column active_years
		dataType: string
		lineageTag: 8269cd0c-ecad-4c4a-b389-997f1cede8c8
		summarizeBy: none
		sourceColumn: active_years

		annotation SummarizationSetBy = Automatic

	column altmetric
		dataType: int64
		formatString: 0
		lineageTag: 65ca240a-d600-4ba7-a646-fd6deb0e7c2c
		summarizeBy: sum
		sourceColumn: altmetric

		annotation SummarizationSetBy = Automatic

	column associated_grant_ids
		dataType: string
		lineageTag: 96e43473-9399-46a1-b095-457216a0393e
		summarizeBy: none
		sourceColumn: associated_grant_ids

		annotation SummarizationSetBy = Automatic

	column brief_title
		dataType: string
		lineageTag: 7ea10875-76d8-4a08-b146-553e9b4888b9
		summarizeBy: none
		sourceColumn: brief_title

		annotation SummarizationSetBy = Automatic

	column category_bra
		dataType: string
		lineageTag: 532b1030-24c9-4df0-8959-46d332737e2b
		summarizeBy: none
		sourceColumn: category_bra

		annotation SummarizationSetBy = Automatic

	column category_for
		dataType: string
		lineageTag: 7ad99f55-b0ca-4491-8b93-c40169619dde
		summarizeBy: none
		sourceColumn: category_for

		annotation SummarizationSetBy = Automatic

	column category_hra
		dataType: string
		lineageTag: 8df18241-ba21-4cfa-bd07-74894ef8cfbe
		summarizeBy: none
		sourceColumn: category_hra

		annotation SummarizationSetBy = Automatic

	column category_hrcs_hc
		dataType: string
		lineageTag: af3fee9a-2535-4017-891c-dd24fb4927c1
		summarizeBy: none
		sourceColumn: category_hrcs_hc

		annotation SummarizationSetBy = Automatic

	column category_hrcs_rac
		dataType: string
		lineageTag: 97e7d972-dc37-4750-82f1-7994b3c882b3
		summarizeBy: none
		sourceColumn: category_hrcs_rac

		annotation SummarizationSetBy = Automatic

	column category_icrp_cso
		dataType: string
		lineageTag: 555cc51b-e371-4405-94b5-5ebc88479ffe
		summarizeBy: none
		sourceColumn: category_icrp_cso

		annotation SummarizationSetBy = Automatic

	column category_icrp_ct
		dataType: string
		lineageTag: 310df08c-2155-4a63-942a-de77d3db16b8
		summarizeBy: none
		sourceColumn: category_icrp_ct

		annotation SummarizationSetBy = Automatic

	column category_rcdc
		dataType: string
		lineageTag: ce319699-33fe-45c1-910d-ff8eb25f73c4
		summarizeBy: none
		sourceColumn: category_rcdc

		annotation SummarizationSetBy = Automatic

	column conditions
		dataType: string
		lineageTag: f2e7fcc9-65f6-483b-a59b-7f3d78c93ef8
		summarizeBy: none
		sourceColumn: conditions

		annotation SummarizationSetBy = Automatic

	column date_inserted
		dataType: dateTime
		formatString: Long Date
		lineageTag: acc55a26-a9e3-440a-9988-bddca67bd7df
		summarizeBy: none
		sourceColumn: date_inserted

		variation Variation
			isDefault
			relationship: 5399f4ad-7af7-41c8-bdc3-7cdc36f7c63f
			defaultHierarchy: LocalDateTable_33d91fd9-725a-4a26-8450-6c69edb335bd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dimensions_url
		dataType: string
		lineageTag: 89b7a2b4-01af-4538-85ed-e7c89421d164
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 63aee949-d20d-44e5-8e14-6c67d7afaaea
		summarizeBy: none
		sourceColumn: end_date

		variation Variation
			isDefault
			relationship: f9d8a861-5683-4b7a-8a8b-f408a580d8ac
			defaultHierarchy: LocalDateTable_d4fd6654-f466-4093-86d2-6d27905bcfbd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column funder_countries
		dataType: string
		lineageTag: 51aa2da1-fa9e-4c24-8ca6-a3ceeb5352cc
		summarizeBy: none
		sourceColumn: funder_countries

		annotation SummarizationSetBy = Automatic

	column funders
		dataType: string
		lineageTag: b2a7b78d-9d7a-438c-9219-8fff8b9e7602
		summarizeBy: none
		sourceColumn: funders

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 2cbc83f0-ff19-4d75-bcf9-8b5b4eed722b
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column interventions
		dataType: string
		lineageTag: 5c1e7d21-9efd-471a-a492-3a2e28f12f5f
		summarizeBy: none
		sourceColumn: interventions

		annotation SummarizationSetBy = Automatic

	column investigators
		dataType: string
		lineageTag: d017889a-c0c5-4118-b8f2-2b24238a771e
		summarizeBy: none
		sourceColumn: investigators

		annotation SummarizationSetBy = Automatic

	column linkout
		dataType: string
		lineageTag: 11725ad3-192d-482f-b6d4-7d1db6958561
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column mesh_terms
		dataType: string
		lineageTag: d6d18ddc-2cd6-44bb-bd74-d55ecb15b916
		summarizeBy: none
		sourceColumn: mesh_terms

		annotation SummarizationSetBy = Automatic

	column overall_status
		dataType: string
		lineageTag: a99fca65-3c5f-482e-83f7-0c197df88ee1
		summarizeBy: none
		sourceColumn: overall_status

		annotation SummarizationSetBy = Automatic

	column phase
		dataType: string
		lineageTag: e92894e5-ba95-43d6-b721-d49221c24011
		summarizeBy: none
		sourceColumn: phase

		annotation SummarizationSetBy = Automatic

	column publication_ids
		dataType: string
		lineageTag: 5912a387-7c49-4c82-b3e8-11453159087d
		summarizeBy: none
		sourceColumn: publication_ids

		annotation SummarizationSetBy = Automatic

	column registry
		dataType: string
		lineageTag: 66565059-7486-4547-a1b1-339c2eaf58d4
		summarizeBy: none
		sourceColumn: registry

		annotation SummarizationSetBy = Automatic

	column research_orgs
		dataType: string
		lineageTag: 4e8680d4-3db0-4f33-8f9e-85b02dae8642
		summarizeBy: none
		sourceColumn: research_orgs

		annotation SummarizationSetBy = Automatic

	column researchers
		dataType: string
		lineageTag: 27115e49-d039-44e5-88fd-dbb35ce301cb
		summarizeBy: none
		sourceColumn: researchers

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 62658310-4e6d-404d-b495-a788d3e5c7dd
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: 3f84e898-4f6c-4778-b9ec-9c5d446ae275
			defaultHierarchy: LocalDateTable_85434187-e582-4811-a71f-4b2f502dd660.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column study_arms
		dataType: string
		lineageTag: 17094c7b-3457-455e-9c85-748403835751
		summarizeBy: none
		sourceColumn: study_arms

		annotation SummarizationSetBy = Automatic

	column study_designs
		dataType: string
		lineageTag: 7e8bdfd7-63e2-43ab-9d96-577fa068ece0
		summarizeBy: none
		sourceColumn: study_designs

		annotation SummarizationSetBy = Automatic

	column study_eligibility_criteria
		dataType: string
		lineageTag: 7cdcb453-21c6-4e54-a9f4-50e5fd2a8f8e
		summarizeBy: none
		sourceColumn: study_eligibility_criteria

		annotation SummarizationSetBy = Automatic

	column study_maximum_age
		dataType: string
		lineageTag: 8e452435-5035-491c-a5b9-9f501e77916e
		summarizeBy: none
		sourceColumn: study_maximum_age

		annotation SummarizationSetBy = Automatic

	column study_minimum_age
		dataType: string
		lineageTag: 1cae37c6-9579-42ad-b2c3-9709f4eabf59
		summarizeBy: none
		sourceColumn: study_minimum_age

		annotation SummarizationSetBy = Automatic

	column study_outcome_measures
		dataType: string
		lineageTag: e7ddb26f-37c8-4cbd-81b7-f77e5ed9306a
		summarizeBy: none
		sourceColumn: study_outcome_measures

		annotation SummarizationSetBy = Automatic

	column study_participants
		dataType: int64
		formatString: 0
		lineageTag: 19edc295-84b9-461f-a0ed-a914355acddb
		summarizeBy: sum
		sourceColumn: study_participants

		annotation SummarizationSetBy = Automatic

	column study_type
		dataType: string
		lineageTag: 1007dfa9-efa8-4d18-9257-c127fbdb1519
		summarizeBy: none
		sourceColumn: study_type

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 53ed01ac-7987-4edf-81cb-1ac2660f57df
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	partition enr_citing_clinical_trial = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    enr_citing_clinical_trial_Sheet = Source{[Item="enr_citing_clinical_trial",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(enr_citing_clinical_trial_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cited_dimensions_id", type text}, {"ct_id", type text}, {"abstract", type text}, {"acronym", type text}, {"active_years", type text}, {"altmetric", Int64.Type}, {"associated_grant_ids", type text}, {"brief_title", type text}, {"category_bra", type text}, {"category_for", type text}, {"category_hra", type text}, {"category_hrcs_hc", type text}, {"category_hrcs_rac", type text}, {"category_icrp_cso", type text}, {"category_icrp_ct", type text}, {"category_rcdc", type text}, {"conditions", type text}, {"date_inserted", type date}, {"dimensions_url", type text}, {"end_date", type date}, {"funder_countries", type text}, {"funders", type text}, {"gender", type text}, {"interventions", type text}, {"investigators", type text}, {"linkout", type text}, {"mesh_terms", type text}, {"overall_status", type text}, {"phase", type text}, {"publication_ids", type text}, {"registry", type text}, {"research_orgs", type text}, {"researchers", type text}, {"start_date", type date}, {"study_arms", type text}, {"study_designs", type text}, {"study_eligibility_criteria", type text}, {"study_maximum_age", type text}, {"study_minimum_age", type text}, {"study_outcome_measures", type text}, {"study_participants", Int64.Type}, {"study_type", type text}, {"title", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

