table raw_pub_citing_publication
	lineageTag: 91d59707-d0c0-4e1a-97c3-7ef8643e4823

	column citing_dimensions_id
		dataType: string
		lineageTag: ae5ab2f3-009f-4b83-a1f6-553613037fd8
		summarizeBy: none
		sourceColumn: citing_dimensions_id

		annotation SummarizationSetBy = Automatic

	column citing_doi
		dataType: string
		lineageTag: ddf9c8a8-a6f6-42a2-a8b1-89d55e29bd28
		summarizeBy: none
		sourceColumn: citing_doi

		annotation SummarizationSetBy = Automatic

	column journal_id
		dataType: string
		lineageTag: e2833b5a-6697-4951-a5cb-84551140cb23
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column journal_title
		dataType: string
		lineageTag: 1d57691b-0a7a-4343-bc47-b3fbf0c4acaf
		summarizeBy: none
		sourceColumn: journal_title

		annotation SummarizationSetBy = Automatic

	column pub_year
		dataType: int64
		formatString: 0
		lineageTag: 18780436-70ba-4da8-a869-287ceaafe521
		summarizeBy: sum
		sourceColumn: pub_year

		annotation SummarizationSetBy = Automatic

	column document_type
		dataType: string
		lineageTag: c7c8e2b3-aea9-468a-8fd5-356b35fff4f6
		summarizeBy: none
		sourceColumn: document_type

		annotation SummarizationSetBy = Automatic

	column times_cited
		dataType: int64
		formatString: 0
		lineageTag: ff124cb1-0b3d-4bd4-af42-022e0ff7ffe2
		summarizeBy: sum
		sourceColumn: times_cited

		annotation SummarizationSetBy = Automatic

	column field_citation_ratio
		dataType: string
		lineageTag: df29619d-f8ae-44cf-b4e6-ffb18a1a1a1f
		summarizeBy: none
		sourceColumn: field_citation_ratio

		annotation SummarizationSetBy = Automatic

	column altmetric_score_citing
		dataType: string
		lineageTag: 31a4a862-fd3a-4371-bade-ea409c59796e
		summarizeBy: none
		sourceColumn: altmetric_score_citing

		annotation SummarizationSetBy = Automatic

	column reference_ids
		dataType: string
		lineageTag: c26df263-04aa-4494-8473-6bf5fac1c510
		summarizeBy: none
		sourceColumn: reference_ids

		annotation SummarizationSetBy = Automatic

	column research_orgs
		dataType: string
		lineageTag: ffb1ac12-b124-4bcb-9c50-c06aa4f7d730
		summarizeBy: none
		sourceColumn: research_orgs

		annotation SummarizationSetBy = Automatic

	partition raw_pub_citing_publication = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    raw_pub_citing_publication_Sheet = Source{[Item="raw_pub_citing_publication",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_pub_citing_publication_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"citing_dimensions_id", type text}, {"citing_doi", type text}, {"journal_id", type text}, {"journal_title", type text}, {"pub_year", Int64.Type}, {"document_type", type text}, {"times_cited", Int64.Type}, {"field_citation_ratio", type any}, {"altmetric_score_citing", type any}, {"reference_ids", type text}, {"research_orgs", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

