table raw_publication
	lineageTag: 67b3da7f-2e2e-412b-8cb9-6b46543b105a

	column doi
		dataType: string
		lineageTag: f826693c-c5cb-47b1-ae22-dd4465be9068
		summarizeBy: none
		sourceColumn: doi

		annotation SummarizationSetBy = Automatic

	column dimensions_id
		dataType: string
		lineageTag: 854966b4-4e99-4df1-a3ea-9aa75e57afff
		summarizeBy: none
		sourceColumn: dimensions_id

		annotation SummarizationSetBy = Automatic

	column tactic_title
		dataType: string
		lineageTag: cf7b442d-47e0-4831-aea4-e6cdef265965
		summarizeBy: none
		sourceColumn: tactic_title

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 11060413-28bb-44a4-b7a8-3caa5e2f77a7
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column tactic_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd497a46-2e42-465c-9b79-618d75849421
		summarizeBy: none
		sourceColumn: tactic_date

		variation Variation
			isDefault
			relationship: 411d6dc5-1032-4c4f-971e-c7ae24523235
			defaultHierarchy: LocalDateTable_27175666-ef16-499c-8c0c-eeb72e3f00b8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column times_cited
		dataType: int64
		formatString: 0
		lineageTag: 447c83fa-5d32-4acb-b41e-509e60cf3e87
		summarizeBy: sum
		sourceColumn: times_cited

		annotation SummarizationSetBy = Automatic

	column document_type
		dataType: string
		lineageTag: ad4ecce1-c996-4538-aef5-d15707c905ea
		summarizeBy: none
		sourceColumn: document_type

		annotation SummarizationSetBy = Automatic

	column altmetric_id
		dataType: string
		lineageTag: 5ef9402c-9a7b-4a7c-bb3e-b928df307c4d
		summarizeBy: none
		sourceColumn: altmetric_id

		annotation SummarizationSetBy = Automatic

	column open_access
		dataType: string
		lineageTag: a98dd136-7cbc-4139-88f3-b7ee34066b94
		summarizeBy: none
		sourceColumn: open_access

		annotation SummarizationSetBy = Automatic

	column recent_citations
		dataType: string
		lineageTag: b85fb8a2-59be-41b7-9f0f-98ac0cef6983
		summarizeBy: none
		sourceColumn: recent_citations

		annotation SummarizationSetBy = Automatic

	column journal_id
		dataType: string
		lineageTag: d9932415-2785-438e-a5f8-d019861d0219
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column arxiv_id
		dataType: string
		lineageTag: 847b8c34-8f9d-47cd-bcb9-281e33ef5480
		summarizeBy: none
		sourceColumn: arxiv_id

		annotation SummarizationSetBy = Automatic

	column abstract
		dataType: string
		lineageTag: acfb74b1-eb29-488c-947f-5a24deacbd3d
		summarizeBy: none
		sourceColumn: abstract

		annotation SummarizationSetBy = Automatic

	column authors
		dataType: string
		lineageTag: ca1d6c47-17f7-4f40-8918-d74aa871f92f
		summarizeBy: none
		sourceColumn: authors

		annotation SummarizationSetBy = Automatic

	column field_citation_ratio
		dataType: string
		lineageTag: 9c29ce3e-6ab8-4a66-9fab-56e2e39a9faa
		summarizeBy: none
		sourceColumn: field_citation_ratio

		annotation SummarizationSetBy = Automatic

	column relative_citation_ratio
		dataType: string
		lineageTag: a315cdc8-77e4-41d2-8c35-fa2935ec43cd
		summarizeBy: none
		sourceColumn: relative_citation_ratio

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 20fd8809-e97f-4792-be6e-c5db7d36159b
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column linkout
		dataType: string
		lineageTag: a808478c-6957-4066-939f-178713c3a1fa
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column mesh_terms
		dataType: string
		lineageTag: e6da696e-a71b-4673-81fb-7a74cf0b373d
		summarizeBy: none
		sourceColumn: mesh_terms

		annotation SummarizationSetBy = Automatic

	column funders_name
		dataType: string
		lineageTag: 367ecb18-1d44-4bc2-a26d-19c14fdf1502
		summarizeBy: none
		sourceColumn: funders_name

		annotation SummarizationSetBy = Automatic

	column category_hra
		dataType: string
		lineageTag: 87d42868-a2cc-4ac2-b3f9-df6dc4a943bf
		summarizeBy: none
		sourceColumn: category_hra

		annotation SummarizationSetBy = Automatic

	column authors_affiliation
		dataType: string
		lineageTag: beff5107-af6f-459d-bfab-76177e3464e1
		summarizeBy: none
		sourceColumn: authors_affiliation

		annotation SummarizationSetBy = Automatic

	column source_origin
		dataType: string
		lineageTag: cf00bf5b-3f4f-4e39-beb3-ee749aefe67c
		summarizeBy: none
		sourceColumn: source_origin

		annotation SummarizationSetBy = Automatic

	column source_origin_keyword
		dataType: string
		lineageTag: 2fd48794-0a4c-446a-bd0d-4ea1a2126982
		summarizeBy: none
		sourceColumn: source_origin_keyword

		annotation SummarizationSetBy = Automatic

	column source_origin_doi
		dataType: string
		lineageTag: b0476b9b-69a9-43ab-a04e-4e2f74d2c2d8
		summarizeBy: none
		sourceColumn: source_origin_doi

		annotation SummarizationSetBy = Automatic

	column source_department
		dataType: string
		lineageTag: b295d5e3-5cae-4ed7-b5ae-03cc3375daed
		summarizeBy: none
		sourceColumn: source_department

		annotation SummarizationSetBy = Automatic

	column acknowledgements
		dataType: string
		lineageTag: c15586ab-d93d-4d0f-9dc7-340a64f767d3
		summarizeBy: none
		sourceColumn: acknowledgements

		annotation SummarizationSetBy = Automatic

	column authors_count
		dataType: string
		lineageTag: cc1f4ea9-7212-43f6-a4a9-b233992f5193
		summarizeBy: none
		sourceColumn: authors_count

		annotation SummarizationSetBy = Automatic

	column book_doi
		dataType: string
		lineageTag: f1ed8613-e034-407f-b16d-a94b7c42ad7f
		summarizeBy: none
		sourceColumn: book_doi

		annotation SummarizationSetBy = Automatic

	column book_series_title
		dataType: string
		lineageTag: 2224b68b-abb4-43ca-95f6-88697c87211c
		summarizeBy: none
		sourceColumn: book_series_title

		annotation SummarizationSetBy = Automatic

	column book_title
		dataType: string
		lineageTag: a39c6b5a-f716-4009-88e8-92804a0afebc
		summarizeBy: none
		sourceColumn: book_title

		annotation SummarizationSetBy = Automatic

	column category_bra
		dataType: string
		lineageTag: 54c117e7-e039-49bf-b9ef-07fb3676f343
		summarizeBy: none
		sourceColumn: category_bra

		annotation SummarizationSetBy = Automatic

	column category_for
		dataType: string
		lineageTag: 5171f68c-6c1f-462a-8596-df26fd9921c7
		summarizeBy: none
		sourceColumn: category_for

		annotation SummarizationSetBy = Automatic

	column category_for_2020
		dataType: string
		lineageTag: e12c296f-61d3-40b4-927e-b7e14380b6c5
		summarizeBy: none
		sourceColumn: category_for_2020

		annotation SummarizationSetBy = Automatic

	column category_hrcs_hc
		dataType: string
		lineageTag: 36a3a26c-1227-467a-8b1c-333858d92a58
		summarizeBy: none
		sourceColumn: category_hrcs_hc

		annotation SummarizationSetBy = Automatic

	column category_hrcs_rac
		dataType: string
		lineageTag: 4259f3a3-640e-4908-bfa7-f62fc31e92b6
		summarizeBy: none
		sourceColumn: category_hrcs_rac

		annotation SummarizationSetBy = Automatic

	column category_icrp_cso
		dataType: string
		lineageTag: a466b2ab-12a1-4489-803e-ebf2f339c50d
		summarizeBy: none
		sourceColumn: category_icrp_cso

		annotation SummarizationSetBy = Automatic

	column category_icrp_ct
		dataType: string
		lineageTag: 6a2ebcef-7153-4be7-ad35-2c1d3a495fa5
		summarizeBy: none
		sourceColumn: category_icrp_ct

		annotation SummarizationSetBy = Automatic

	column category_rcdc
		dataType: string
		lineageTag: 022eabc0-5fef-4daf-99d4-547ea8d76f7f
		summarizeBy: none
		sourceColumn: category_rcdc

		annotation SummarizationSetBy = Automatic

	column category_sdg
		dataType: string
		lineageTag: 9dea1711-cfd1-4fc9-be63-98e70ae1b4e4
		summarizeBy: none
		sourceColumn: category_sdg

		annotation SummarizationSetBy = Automatic

	column category_uoa
		dataType: string
		lineageTag: 72854834-cf32-41ca-8fe3-a9a6f4ce03d9
		summarizeBy: none
		sourceColumn: category_uoa

		annotation SummarizationSetBy = Automatic

	column clinical_trial_ids
		dataType: string
		lineageTag: d3ad87a8-5f05-4f86-bc07-9e61e9e0312a
		summarizeBy: none
		sourceColumn: clinical_trial_ids

		annotation SummarizationSetBy = Automatic

	column concepts
		dataType: string
		lineageTag: b6d4d4b9-a188-411f-bc45-5a39d341b12e
		summarizeBy: none
		sourceColumn: concepts

		annotation SummarizationSetBy = Automatic

	column concepts_relevant
		dataType: string
		lineageTag: 60492229-dde9-4cf4-bc95-e12e97292221
		summarizeBy: none
		sourceColumn: concepts_relevant

		annotation SummarizationSetBy = Automatic

	column concepts_scores
		dataType: string
		lineageTag: e74e69de-5127-4d02-982e-5703c497a68c
		summarizeBy: none
		sourceColumn: concepts_scores

		annotation SummarizationSetBy = Automatic

	column date_inserted
		dataType: string
		lineageTag: 1a5525df-c034-41a2-b4d0-08c0d5b0f343
		summarizeBy: none
		sourceColumn: date_inserted

		annotation SummarizationSetBy = Automatic

	column date_online
		dataType: string
		lineageTag: 2a4d4c08-83ab-4866-8f79-0a67b74ad686
		summarizeBy: none
		sourceColumn: date_online

		annotation SummarizationSetBy = Automatic

	column date_print
		dataType: string
		lineageTag: 3843ccc8-2fa6-4e82-b957-a09264675030
		summarizeBy: none
		sourceColumn: date_print

		annotation SummarizationSetBy = Automatic

	column editors
		dataType: string
		lineageTag: 88b7eb7c-028b-455c-bec2-c47cdd3f3006
		summarizeBy: none
		sourceColumn: editors

		annotation SummarizationSetBy = Automatic

	column funder_countries
		dataType: string
		lineageTag: f0e8283d-35c7-4b05-aa0d-20a95507070e
		summarizeBy: none
		sourceColumn: funder_countries

		annotation SummarizationSetBy = Automatic

	column funding_section
		dataType: string
		lineageTag: feee30da-102a-49b4-9762-02d7accee0b3
		summarizeBy: none
		sourceColumn: funding_section

		annotation SummarizationSetBy = Automatic

	column isbn
		dataType: string
		lineageTag: 94f91e42-f016-4439-89fb-4448cde625ad
		summarizeBy: none
		sourceColumn: isbn

		annotation SummarizationSetBy = Automatic

	column issn
		dataType: string
		lineageTag: 1188ed65-dc28-4982-895f-83f98d9288b3
		summarizeBy: none
		sourceColumn: issn

		annotation SummarizationSetBy = Automatic

	column issue
		dataType: string
		lineageTag: 11364b07-53d0-46c3-ab1a-91b898a4987c
		summarizeBy: none
		sourceColumn: issue

		annotation SummarizationSetBy = Automatic

	column journal_lists
		dataType: string
		lineageTag: 8ba97759-40c5-44d3-9d5e-fa24114c5643
		summarizeBy: none
		sourceColumn: journal_lists

		annotation SummarizationSetBy = Automatic

	column journal_title_raw
		dataType: string
		lineageTag: 021af44c-5719-4b74-8d03-e863e92b810e
		summarizeBy: none
		sourceColumn: journal_title_raw

		annotation SummarizationSetBy = Automatic

	column pages
		dataType: string
		lineageTag: feb8f7c0-2cc6-4f32-9dec-ef29e9272356
		summarizeBy: none
		sourceColumn: pages

		annotation SummarizationSetBy = Automatic

	column pmcid
		dataType: string
		lineageTag: c03f5782-b2c2-46bc-825f-cd632b8ac6e9
		summarizeBy: none
		sourceColumn: pmcid

		annotation SummarizationSetBy = Automatic

	column pmid
		dataType: int64
		formatString: 0
		lineageTag: 02782793-3f11-4ac0-a499-d5f9f23eb9b4
		summarizeBy: sum
		sourceColumn: pmid

		annotation SummarizationSetBy = Automatic

	column proceedings_title
		dataType: string
		lineageTag: 03d80f2d-fdf4-438e-b9be-631b459aa0ed
		summarizeBy: none
		sourceColumn: proceedings_title

		annotation SummarizationSetBy = Automatic

	column publisher
		dataType: string
		lineageTag: a45e63de-68f9-4518-ac71-905773585811
		summarizeBy: none
		sourceColumn: publisher

		annotation SummarizationSetBy = Automatic

	column referenced_pubs
		dataType: string
		lineageTag: 85bf0669-c0f9-4be0-b6ae-448e19bbcb4b
		summarizeBy: none
		sourceColumn: referenced_pubs

		annotation SummarizationSetBy = Automatic

	column research_org_cities
		dataType: string
		lineageTag: bcb37fb8-40f9-4f32-89eb-fc98448e6b59
		summarizeBy: none
		sourceColumn: research_org_cities

		annotation SummarizationSetBy = Automatic

	column research_org_countries
		dataType: string
		lineageTag: 921f0290-01e8-4895-a5a9-337d1cb52aa3
		summarizeBy: none
		sourceColumn: research_org_countries

		annotation SummarizationSetBy = Automatic

	column research_org_state_codes
		dataType: string
		lineageTag: 77aa70c7-a6d7-4d94-b612-2d19668475cc
		summarizeBy: none
		sourceColumn: research_org_state_codes

		annotation SummarizationSetBy = Automatic

	column research_org_types
		dataType: string
		lineageTag: da782406-6db5-46ba-a766-01e4ab8bb27d
		summarizeBy: none
		sourceColumn: research_org_types

		annotation SummarizationSetBy = Automatic

	column resulting_publication_doi
		dataType: string
		lineageTag: d283164a-c92b-446b-b3b0-787ebfd26db5
		summarizeBy: none
		sourceColumn: resulting_publication_doi

		annotation SummarizationSetBy = Automatic

	column relevance_score
		dataType: string
		lineageTag: 4774d0cf-758e-49a4-bdba-b9a5d6759161
		summarizeBy: none
		sourceColumn: relevance_score

		annotation SummarizationSetBy = Automatic

	column source_title
		dataType: string
		lineageTag: 223aa721-7325-4c27-a206-3b0d08525354
		summarizeBy: none
		sourceColumn: source_title

		annotation SummarizationSetBy = Automatic

	column subtitles
		dataType: string
		lineageTag: 8777d0fe-ce94-49b9-b81e-de796bf55843
		summarizeBy: none
		sourceColumn: subtitles

		annotation SummarizationSetBy = Automatic

	column supporting_grant_ids
		dataType: string
		lineageTag: 3b1ca26c-28b8-41dc-b2eb-27c566d2a2b7
		summarizeBy: none
		sourceColumn: supporting_grant_ids

		annotation SummarizationSetBy = Automatic

	column publication_type
		dataType: string
		lineageTag: cd4e88fe-a808-4268-a1d6-7860e1ca7609
		summarizeBy: none
		sourceColumn: publication_type

		annotation SummarizationSetBy = Automatic

	column volume
		dataType: int64
		formatString: 0
		lineageTag: ff0b7e74-118c-406e-8482-7e2679decb9c
		summarizeBy: sum
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

	partition raw_publication = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    raw_publication_Sheet = Source{[Item="raw_publication",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_publication_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"doi", type text}, {"dimensions_id", type text}, {"tactic_title", type text}, {"channel", type text}, {"tactic_date", type date}, {"times_cited", Int64.Type}, {"document_type", type any}, {"altmetric_id", type any}, {"open_access", type text}, {"recent_citations", type any}, {"journal_id", type text}, {"arxiv_id", type any}, {"abstract", type text}, {"authors", type text}, {"field_citation_ratio", type any}, {"relative_citation_ratio", type any}, {"dimensions_url", type text}, {"linkout", type text}, {"mesh_terms", type text}, {"funders_name", type text}, {"category_hra", type text}, {"authors_affiliation", type text}, {"source_origin", type text}, {"source_origin_keyword", type any}, {"source_origin_doi", type text}, {"source_department", type any}, {"acknowledgements", type any}, {"authors_count", type any}, {"book_doi", type any}, {"book_series_title", type any}, {"book_title", type any}, {"category_bra", type text}, {"category_for", type text}, {"category_for_2020", type any}, {"category_hrcs_hc", type text}, {"category_hrcs_rac", type text}, {"category_icrp_cso", type text}, {"category_icrp_ct", type text}, {"category_rcdc", type text}, {"category_sdg", type text}, {"category_uoa", type text}, {"clinical_trial_ids", type any}, {"concepts", type any}, {"concepts_relevant", type any}, {"concepts_scores", type any}, {"date_inserted", type any}, {"date_online", type any}, {"date_print", type any}, {"editors", type any}, {"funder_countries", type any}, {"funding_section", type any}, {"isbn", type any}, {"issn", type any}, {"issue", type text}, {"journal_lists", type text}, {"journal_title_raw", type text}, {"pages", type text}, {"pmcid", type text}, {"pmid", Int64.Type}, {"proceedings_title", type any}, {"publisher", type any}, {"referenced_pubs", type any}, {"research_org_cities", type text}, {"research_org_countries", type text}, {"research_org_state_codes", type text}, {"research_org_types", type any}, {"resulting_publication_doi", type any}, {"relevance_score", type any}, {"source_title", type any}, {"subtitles", type any}, {"supporting_grant_ids", type any}, {"publication_type", type text}, {"volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

