table raw_clinical_trial
	lineageTag: 44abd9b4-22ae-4546-88bb-8eac176470f8

	column Column1
		dataType: string
		lineageTag: 5660c73e-e079-45c9-9a32-03324b2fdbd2
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 1803276e-4cbb-4cb0-8e27-23a77b97f590
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 555a8569-f5b5-4693-b075-44c7c662e77f
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition raw_clinical_trial = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    raw_clinical_trial_Sheet = Source{[Item="raw_clinical_trial",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(raw_clinical_trial_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

