table raw_journal_stats
	lineageTag: 36146fd9-1f6a-4daf-bb78-8b891c4f562c

	column journal_id
		dataType: string
		lineageTag: 3c054dff-4ce8-4f45-b236-d91c6bde02e8
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column journal_title
		dataType: string
		lineageTag: 6e865cfd-7575-4a46-9f52-0ab4696e9ac2
		summarizeBy: none
		sourceColumn: journal_title

		annotation SummarizationSetBy = Automatic

	column publisher_country
		dataType: string
		lineageTag: ace10a95-010c-4dfe-897d-ea5dcf9d580c
		summarizeBy: none
		sourceColumn: publisher_country

		annotation SummarizationSetBy = Automatic

	column category_hra
		dataType: string
		lineageTag: fccc1de1-6383-4070-86b8-53a32d9f16d7
		summarizeBy: none
		sourceColumn: category_hra

		annotation SummarizationSetBy = Automatic

	column citations_total
		dataType: int64
		formatString: 0
		lineageTag: edc6548f-7ef0-4eb0-9d29-0bd87027e48a
		summarizeBy: sum
		sourceColumn: citations_total

		annotation SummarizationSetBy = Automatic

	column paper_count
		dataType: int64
		formatString: 0
		lineageTag: f01dc785-3a10-4182-8224-e16fdcbfb74e
		summarizeBy: sum
		sourceColumn: paper_count

		annotation SummarizationSetBy = Automatic

	partition raw_journal_stats = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    raw_journal_stats_Sheet = Source{[Item="raw_journal_stats",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_journal_stats_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"journal_id", type text}, {"journal_title", type text}, {"publisher_country", type any}, {"category_hra", type any}, {"citations_total", Int64.Type}, {"paper_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

