table raw_citing_clinical_trial
	lineageTag: be912135-9ea0-4cc7-8883-bf44bce81bdf

	column cited_dimensions_id
		dataType: string
		lineageTag: c6147b04-55cc-4e65-99db-7d054df3a27f
		summarizeBy: none
		sourceColumn: cited_dimensions_id

		annotation SummarizationSetBy = Automatic

	column ct_id
		dataType: string
		lineageTag: 221601ee-0ed2-48d7-9c9c-ec6eb776b3c7
		summarizeBy: none
		sourceColumn: ct_id

		annotation SummarizationSetBy = Automatic

	column abstract
		dataType: string
		lineageTag: 9f6553b7-fa83-4846-87a4-6c4001a8f18a
		summarizeBy: none
		sourceColumn: abstract

		annotation SummarizationSetBy = Automatic

	column acronym
		dataType: string
		lineageTag: 30c52edc-c1e1-4c52-8842-4a9e28fd6cba
		summarizeBy: none
		sourceColumn: acronym

		annotation SummarizationSetBy = Automatic

	column active_years
		dataType: string
		lineageTag: f7e13155-3c82-4ab7-aeb7-68a16be03345
		summarizeBy: none
		sourceColumn: active_years

		annotation SummarizationSetBy = Automatic

	column altmetric
		dataType: int64
		formatString: 0
		lineageTag: d4290fbc-f4a8-4ed4-ae5c-62e07b68438a
		summarizeBy: sum
		sourceColumn: altmetric

		annotation SummarizationSetBy = Automatic

	column associated_grant_ids
		dataType: string
		lineageTag: 06527b0a-47dc-4e78-8eea-2052ee57e3ff
		summarizeBy: none
		sourceColumn: associated_grant_ids

		annotation SummarizationSetBy = Automatic

	column brief_title
		dataType: string
		lineageTag: 27419a5b-09bb-4825-9829-960fb4f4b62c
		summarizeBy: none
		sourceColumn: brief_title

		annotation SummarizationSetBy = Automatic

	column category_bra
		dataType: string
		lineageTag: 05dc1f9e-ea90-4a3b-bbc1-dd3b9a1528fc
		summarizeBy: none
		sourceColumn: category_bra

		annotation SummarizationSetBy = Automatic

	column category_for
		dataType: string
		lineageTag: 316a69fe-2c41-4c61-8ef1-9addcc13b537
		summarizeBy: none
		sourceColumn: category_for

		annotation SummarizationSetBy = Automatic

	column category_hra
		dataType: string
		lineageTag: a12adfba-9309-41eb-8fe7-daf179a59865
		summarizeBy: none
		sourceColumn: category_hra

		annotation SummarizationSetBy = Automatic

	column category_hrcs_hc
		dataType: string
		lineageTag: c6d5f321-df86-416f-9bdc-94768ca6b50e
		summarizeBy: none
		sourceColumn: category_hrcs_hc

		annotation SummarizationSetBy = Automatic

	column category_hrcs_rac
		dataType: string
		lineageTag: eca13c4e-ff7d-4def-b833-88a2bc83456c
		summarizeBy: none
		sourceColumn: category_hrcs_rac

		annotation SummarizationSetBy = Automatic

	column category_icrp_cso
		dataType: string
		lineageTag: e7782888-86c1-4f55-bf51-272c0a861b6c
		summarizeBy: none
		sourceColumn: category_icrp_cso

		annotation SummarizationSetBy = Automatic

	column category_icrp_ct
		dataType: string
		lineageTag: af7cc4d3-0363-4c76-ac23-39a57b9ca958
		summarizeBy: none
		sourceColumn: category_icrp_ct

		annotation SummarizationSetBy = Automatic

	column category_rcdc
		dataType: string
		lineageTag: 4e0eb5a0-a05e-4303-9692-b887249f142a
		summarizeBy: none
		sourceColumn: category_rcdc

		annotation SummarizationSetBy = Automatic

	column conditions
		dataType: string
		lineageTag: c3ea1451-8d91-4305-9eaa-f559ea561236
		summarizeBy: none
		sourceColumn: conditions

		annotation SummarizationSetBy = Automatic

	column date_inserted
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9152b7d6-0fb1-4ebb-9e5b-4f99d0c2b3a1
		summarizeBy: none
		sourceColumn: date_inserted

		variation Variation
			isDefault
			relationship: bbbb1399-f539-45e0-bb5c-6c5e44211c3a
			defaultHierarchy: LocalDateTable_dbc849eb-de65-427b-96df-61368ce9302d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dimensions_url
		dataType: string
		lineageTag: 35fffaae-085d-4c42-ab33-c5eb637f6fb6
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1fe7cdd4-4c98-42e8-9268-97914d4069c3
		summarizeBy: none
		sourceColumn: end_date

		variation Variation
			isDefault
			relationship: 8dbdc421-fff7-482c-9195-932e1e78b05e
			defaultHierarchy: LocalDateTable_9478a629-8a21-4b55-965e-413bdad38564.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column funder_countries
		dataType: string
		lineageTag: 1a71e280-90d7-4739-9519-739ae1625134
		summarizeBy: none
		sourceColumn: funder_countries

		annotation SummarizationSetBy = Automatic

	column funders
		dataType: string
		lineageTag: 67c5b112-1996-4032-b4cc-4664590a17f4
		summarizeBy: none
		sourceColumn: funders

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 9f62e209-64e4-4b7c-8aec-d3268fb561cc
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column interventions
		dataType: string
		lineageTag: 117201da-2b40-428e-9485-bc64f5426290
		summarizeBy: none
		sourceColumn: interventions

		annotation SummarizationSetBy = Automatic

	column investigators
		dataType: string
		lineageTag: 56a05a4c-2c9f-40a3-a0bc-6807b90d8c2b
		summarizeBy: none
		sourceColumn: investigators

		annotation SummarizationSetBy = Automatic

	column linkout
		dataType: string
		lineageTag: 87747a79-e4df-4271-be0e-4804f531153c
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column mesh_terms
		dataType: string
		lineageTag: 7e9a9b11-b349-4584-91d5-b8efd36dc9a2
		summarizeBy: none
		sourceColumn: mesh_terms

		annotation SummarizationSetBy = Automatic

	column overall_status
		dataType: string
		lineageTag: 07909f0d-1ea5-46e5-bf3e-74d1b266008c
		summarizeBy: none
		sourceColumn: overall_status

		annotation SummarizationSetBy = Automatic

	column phase
		dataType: string
		lineageTag: 3d8a496f-e57b-4133-a772-8c7723864033
		summarizeBy: none
		sourceColumn: phase

		annotation SummarizationSetBy = Automatic

	column publication_ids
		dataType: string
		lineageTag: 8b38602e-3a29-40fd-af24-53f418657a8a
		summarizeBy: none
		sourceColumn: publication_ids

		annotation SummarizationSetBy = Automatic

	column registry
		dataType: string
		lineageTag: 47ba6402-f354-4406-a118-ff56aa2ada7c
		summarizeBy: none
		sourceColumn: registry

		annotation SummarizationSetBy = Automatic

	column research_orgs
		dataType: string
		lineageTag: a95e2c9d-5753-4c5c-aca0-4f2847127e61
		summarizeBy: none
		sourceColumn: research_orgs

		annotation SummarizationSetBy = Automatic

	column researchers
		dataType: string
		lineageTag: eb7ff193-cbaa-44da-9afe-7b478b166bad
		summarizeBy: none
		sourceColumn: researchers

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 255e0c42-58a5-49af-b639-6ba72b77c225
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: 73bdfc69-bb86-45a8-af8f-1420178872f0
			defaultHierarchy: LocalDateTable_86025d48-2b23-4177-94cc-cd02cfe7db0f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column study_arms
		dataType: string
		lineageTag: 2048a7ac-2768-4652-b33e-b14e1e66f96c
		summarizeBy: none
		sourceColumn: study_arms

		annotation SummarizationSetBy = Automatic

	column study_designs
		dataType: string
		lineageTag: aafac707-853a-4ba0-bdbe-34e94528e4be
		summarizeBy: none
		sourceColumn: study_designs

		annotation SummarizationSetBy = Automatic

	column study_eligibility_criteria
		dataType: string
		lineageTag: 27a9b1ea-f1b6-43aa-a15b-58b3855925c9
		summarizeBy: none
		sourceColumn: study_eligibility_criteria

		annotation SummarizationSetBy = Automatic

	column study_maximum_age
		dataType: string
		lineageTag: 7c48cde9-9853-4584-9446-db2fe675e0c0
		summarizeBy: none
		sourceColumn: study_maximum_age

		annotation SummarizationSetBy = Automatic

	column study_minimum_age
		dataType: string
		lineageTag: 0abb8e0d-00b0-40d8-9697-b4fa3bf96dac
		summarizeBy: none
		sourceColumn: study_minimum_age

		annotation SummarizationSetBy = Automatic

	column study_outcome_measures
		dataType: string
		lineageTag: 09e57ca1-a434-4d5f-bb6c-c94e7588cf52
		summarizeBy: none
		sourceColumn: study_outcome_measures

		annotation SummarizationSetBy = Automatic

	column study_participants
		dataType: int64
		formatString: 0
		lineageTag: b0fb659f-b240-4ee8-bfb8-9ae455ffe207
		summarizeBy: sum
		sourceColumn: study_participants

		annotation SummarizationSetBy = Automatic

	column study_type
		dataType: string
		lineageTag: fdbaee78-45b9-46de-9fbc-bb1e81ee7279
		summarizeBy: none
		sourceColumn: study_type

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 3bdfcae0-2187-4001-b737-4627225131d9
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	partition raw_citing_clinical_trial = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    raw_citing_clinical_trial_Sheet = Source{[Item="raw_citing_clinical_trial",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_citing_clinical_trial_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cited_dimensions_id", type text}, {"ct_id", type text}, {"abstract", type text}, {"acronym", type text}, {"active_years", type text}, {"altmetric", Int64.Type}, {"associated_grant_ids", type text}, {"brief_title", type text}, {"category_bra", type text}, {"category_for", type text}, {"category_hra", type text}, {"category_hrcs_hc", type text}, {"category_hrcs_rac", type text}, {"category_icrp_cso", type text}, {"category_icrp_ct", type text}, {"category_rcdc", type text}, {"conditions", type text}, {"date_inserted", type date}, {"dimensions_url", type text}, {"end_date", type date}, {"funder_countries", type text}, {"funders", type text}, {"gender", type text}, {"interventions", type text}, {"investigators", type text}, {"linkout", type text}, {"mesh_terms", type text}, {"overall_status", type text}, {"phase", type text}, {"publication_ids", type text}, {"registry", type text}, {"research_orgs", type text}, {"researchers", type text}, {"start_date", type date}, {"study_arms", type text}, {"study_designs", type text}, {"study_eligibility_criteria", type text}, {"study_maximum_age", type text}, {"study_minimum_age", type text}, {"study_outcome_measures", type text}, {"study_participants", Int64.Type}, {"study_type", type text}, {"title", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

