table raw_researcher
	lineageTag: 89adf6cb-0aba-4a92-8747-ea37107d3129

	column source_dimensions_id
		dataType: string
		lineageTag: b349fae4-daaa-40b7-9a6e-db6b7892836b
		summarizeBy: none
		sourceColumn: source_dimensions_id

		annotation SummarizationSetBy = Automatic

	column researcher_id
		dataType: string
		lineageTag: 302e629c-9f7c-40df-ba41-215705812272
		summarizeBy: none
		sourceColumn: researcher_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 737fe7a7-da8f-4fa6-b5d8-d9569d34297e
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 28a6c9e2-d732-464b-bedb-be07045902c4
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column orcid_id
		dataType: string
		lineageTag: 2a627f40-4ecb-4078-9acc-7fbb733df7c3
		summarizeBy: none
		sourceColumn: orcid_id

		annotation SummarizationSetBy = Automatic

	column current_research_org
		dataType: string
		lineageTag: 9f7408c8-103e-48a3-8313-6bc0c5313884
		summarizeBy: none
		sourceColumn: current_research_org

		annotation SummarizationSetBy = Automatic

	column research_orgs
		dataType: string
		lineageTag: cddd7815-6147-4f5a-a634-ea9f3d5e5efc
		summarizeBy: none
		sourceColumn: research_orgs

		annotation SummarizationSetBy = Automatic

	column first_grant_year
		dataType: int64
		formatString: 0
		lineageTag: b7f17ce2-f1ad-4313-9d88-2bdc84f77ecc
		summarizeBy: sum
		sourceColumn: first_grant_year

		annotation SummarizationSetBy = Automatic

	column last_grant_year
		dataType: int64
		formatString: 0
		lineageTag: 13485a43-7a12-45f0-8958-222fd992c6ea
		summarizeBy: sum
		sourceColumn: last_grant_year

		annotation SummarizationSetBy = Automatic

	column first_publication_year
		dataType: int64
		formatString: 0
		lineageTag: 48ca1eef-40af-4f27-b059-4cf03dab89d2
		summarizeBy: sum
		sourceColumn: first_publication_year

		annotation SummarizationSetBy = Automatic

	column last_publication_year
		dataType: int64
		formatString: 0
		lineageTag: 1a8dabff-93bc-464f-a0da-b5c2f8c07ccb
		summarizeBy: sum
		sourceColumn: last_publication_year

		annotation SummarizationSetBy = Automatic

	column total_grants
		dataType: int64
		formatString: 0
		lineageTag: 83b4d98c-3c7b-405d-919f-89615ceb9e0b
		summarizeBy: sum
		sourceColumn: total_grants

		annotation SummarizationSetBy = Automatic

	column total_publications
		dataType: int64
		formatString: 0
		lineageTag: adcbb175-5556-4b9d-8809-cc2ac81fd334
		summarizeBy: sum
		sourceColumn: total_publications

		annotation SummarizationSetBy = Automatic

	column nih_ppid
		dataType: int64
		formatString: 0
		lineageTag: 093a7eaa-68f4-4d9d-932b-8c66454b7d8d
		summarizeBy: sum
		sourceColumn: nih_ppid

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 53fea36e-4199-4ad2-8caa-38d1396ab4fd
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column obsolete
		dataType: int64
		formatString: 0
		lineageTag: 9503011e-a9bf-4056-87b4-7fb1ede283df
		summarizeBy: sum
		sourceColumn: obsolete

		annotation SummarizationSetBy = Automatic

	column redirect
		dataType: string
		lineageTag: 3ebd30b1-9443-4641-b8cb-de75b8899a57
		summarizeBy: none
		sourceColumn: redirect

		annotation SummarizationSetBy = Automatic

	column relevance_score
		dataType: string
		lineageTag: c79e3284-354a-4f38-be8d-bcbb0da9750a
		summarizeBy: none
		sourceColumn: relevance_score

		annotation SummarizationSetBy = Automatic

	partition raw_researcher = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    raw_researcher_Sheet = Source{[Item="raw_researcher",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_researcher_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_dimensions_id", type text}, {"researcher_id", type text}, {"first_name", type text}, {"last_name", type text}, {"orcid_id", type text}, {"current_research_org", type text}, {"research_orgs", type text}, {"first_grant_year", Int64.Type}, {"last_grant_year", Int64.Type}, {"first_publication_year", Int64.Type}, {"last_publication_year", Int64.Type}, {"total_grants", Int64.Type}, {"total_publications", Int64.Type}, {"nih_ppid", Int64.Type}, {"dimensions_url", type text}, {"obsolete", Int64.Type}, {"redirect", type text}, {"relevance_score", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

