table raw_gsk_org_lookup
	lineageTag: a4a5bb9a-e1b4-4bae-ae56-f17f1b3178ac

	column Column1
		dataType: string
		lineageTag: 6bb79966-e480-483b-bcac-a1af405f20ec
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 1067bc3d-898f-4646-bf80-c7aa0f5ac59b
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 36cf1e45-e855-4cf4-9c7d-b9a397161f63
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition raw_gsk_org_lookup = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    raw_gsk_org_lookup_Sheet = Source{[Item="raw_gsk_org_lookup",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(raw_gsk_org_lookup_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

