table sd_altmetric
	lineageTag: ef39092a-2472-469f-9e2b-ca8c2f73b158

	column doi
		dataType: string
		lineageTag: 907b0637-1231-4aac-b22f-ff03e3e15891
		summarizeBy: none
		sourceColumn: doi

		annotation SummarizationSetBy = Automatic

	column altmetric_id
		dataType: int64
		formatString: 0
		lineageTag: b63b6712-fe50-4131-b013-75c023b7a26c
		summarizeBy: sum
		sourceColumn: altmetric_id

		annotation SummarizationSetBy = Automatic

	column altmetric_publication_date
		dataType: int64
		formatString: 0
		lineageTag: 334328bd-d9f2-476d-ab29-b00e6c5101ea
		summarizeBy: sum
		sourceColumn: altmetric_publication_date

		annotation SummarizationSetBy = Automatic

	column journal
		dataType: string
		lineageTag: 984e2b63-2118-4128-a0b2-28ee88e9c0a2
		summarizeBy: none
		sourceColumn: journal

		annotation SummarizationSetBy = Automatic

	column cited_by_posts_count
		dataType: int64
		formatString: 0
		lineageTag: 7f3ab0a4-941f-4b4b-ac6e-a58e07cf44a1
		summarizeBy: sum
		sourceColumn: cited_by_posts_count

		annotation SummarizationSetBy = Automatic

	column cited_by_tweeters_count
		dataType: int64
		formatString: 0
		lineageTag: bd427c4a-f114-4307-adfe-783d6af212a3
		summarizeBy: sum
		sourceColumn: cited_by_tweeters_count

		annotation SummarizationSetBy = Automatic

	column cited_by_bluesky_count
		dataType: int64
		formatString: 0
		lineageTag: 54c228b3-ee4d-4cc0-8d4e-3d84074bc026
		summarizeBy: sum
		sourceColumn: cited_by_bluesky_count

		annotation SummarizationSetBy = Automatic

	column cited_by_msm_count
		dataType: int64
		formatString: 0
		lineageTag: 0bc2a501-ade9-46a5-8087-696aca23ef89
		summarizeBy: sum
		sourceColumn: cited_by_msm_count

		annotation SummarizationSetBy = Automatic

	column cited_by_feeds_count
		dataType: int64
		formatString: 0
		lineageTag: a2cd7a4a-c07f-424c-8253-198cfbf1fd12
		summarizeBy: sum
		sourceColumn: cited_by_feeds_count

		annotation SummarizationSetBy = Automatic

	column cited_by_guidelines_count
		dataType: int64
		formatString: 0
		lineageTag: 9879a642-3bcd-4a2c-9e0f-da805f63d8ad
		summarizeBy: sum
		sourceColumn: cited_by_guidelines_count

		annotation SummarizationSetBy = Automatic

	column cited_by_patents_count
		dataType: int64
		formatString: 0
		lineageTag: 427df91f-e140-442b-97f1-5f98d4616c9a
		summarizeBy: sum
		sourceColumn: cited_by_patents_count

		annotation SummarizationSetBy = Automatic

	column n_doc_mentions
		dataType: int64
		formatString: 0
		lineageTag: 87ab79f5-687f-4777-806d-61acb61ea75a
		summarizeBy: sum
		sourceColumn: n_doc_mentions

		annotation SummarizationSetBy = Automatic

	column n_sci_mentions
		dataType: int64
		formatString: 0
		lineageTag: 4b33bc29-2124-438a-8b43-df9a6c6702d7
		summarizeBy: sum
		sourceColumn: n_sci_mentions

		annotation SummarizationSetBy = Automatic

	column n_com_mentions
		dataType: int64
		formatString: 0
		lineageTag: e5568aaf-975d-460c-8b84-07075572b354
		summarizeBy: sum
		sourceColumn: n_com_mentions

		annotation SummarizationSetBy = Automatic

	column n_pub_mentions
		dataType: int64
		formatString: 0
		lineageTag: 8450da4d-ad11-4434-9d47-3230771b24f6
		summarizeBy: sum
		sourceColumn: n_pub_mentions

		annotation SummarizationSetBy = Automatic

	column n_practitioner_mentions
		dataType: int64
		formatString: 0
		lineageTag: fc378f5b-4765-4f62-967d-43c933fa114d
		summarizeBy: sum
		sourceColumn: n_practitioner_mentions

		annotation SummarizationSetBy = Automatic

	column n_researcher_mentions
		dataType: int64
		formatString: 0
		lineageTag: 0335d782-f9c9-44ec-bb8e-fabadea24ca4
		summarizeBy: sum
		sourceColumn: n_researcher_mentions

		annotation SummarizationSetBy = Automatic

	column n_science_communicator_mentions
		dataType: int64
		formatString: 0
		lineageTag: ae6702b5-3bbe-4754-bea5-1de4bcb9c9c2
		summarizeBy: sum
		sourceColumn: n_science_communicator_mentions

		annotation SummarizationSetBy = Automatic

	column n_members_of_public_mentions
		dataType: int64
		formatString: 0
		lineageTag: e10e84f9-1bfb-4f05-a82e-b11af544e596
		summarizeBy: sum
		sourceColumn: n_members_of_public_mentions

		annotation SummarizationSetBy = Automatic

	column mendeley_readers
		dataType: int64
		formatString: 0
		lineageTag: 02f9a019-38a6-46e5-ae90-ba478e684d4f
		summarizeBy: sum
		sourceColumn: mendeley_readers

		annotation SummarizationSetBy = Automatic

	column altmetric_score
		dataType: double
		lineageTag: 4dc1ffa1-8911-4da5-bb90-26021bd9e82d
		summarizeBy: sum
		sourceColumn: altmetric_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pmid
		dataType: int64
		formatString: 0
		lineageTag: 487d3172-4f0e-41a8-a76f-54b57dba4450
		summarizeBy: sum
		sourceColumn: pmid

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 3938ba37-77cc-40a3-878d-01157f5500a2
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column score
		dataType: double
		lineageTag: 0e4e1c59-1b90-4bea-910d-064552b13a0c
		summarizeBy: sum
		sourceColumn: score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column score_1d
		dataType: int64
		formatString: 0
		lineageTag: b40d6298-3345-4ec1-898f-bfde7d2f6ad8
		summarizeBy: sum
		sourceColumn: score_1d

		annotation SummarizationSetBy = Automatic

	column score_1w
		dataType: int64
		formatString: 0
		lineageTag: f6bea1b5-ab92-4d5b-a0e8-1e9bb4c75c84
		summarizeBy: sum
		sourceColumn: score_1w

		annotation SummarizationSetBy = Automatic

	column score_1m
		dataType: int64
		formatString: 0
		lineageTag: 3c285363-f4d7-434f-b23f-7a15d8b441d0
		summarizeBy: sum
		sourceColumn: score_1m

		annotation SummarizationSetBy = Automatic

	column score_3m
		dataType: double
		lineageTag: d99b6ee3-cff0-414d-b03f-dedfbd0c6f30
		summarizeBy: sum
		sourceColumn: score_3m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column score_6m
		dataType: double
		lineageTag: 8b416cbc-2216-4897-8139-f2ebdb540450
		summarizeBy: sum
		sourceColumn: score_6m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column score_1y
		dataType: double
		lineageTag: b8280bf5-913b-427f-8555-088e1e8992a4
		summarizeBy: sum
		sourceColumn: score_1y

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column context_all_mean
		dataType: double
		lineageTag: 44bb942b-f7a3-466d-b46c-39ebbaf9310f
		summarizeBy: sum
		sourceColumn: context_all_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column context_all_rank
		dataType: int64
		formatString: 0
		lineageTag: a6da45c9-b370-477d-b3c5-3421d257eeee
		summarizeBy: sum
		sourceColumn: context_all_rank

		annotation SummarizationSetBy = Automatic

	column context_all_pct
		dataType: int64
		formatString: 0
		lineageTag: b433a014-855a-4cb6-9b8b-d3abae11cd98
		summarizeBy: sum
		sourceColumn: context_all_pct

		annotation SummarizationSetBy = Automatic

	column context_journal_mean
		dataType: double
		lineageTag: 08aba742-eea2-4d8b-b449-e9718db1250f
		summarizeBy: sum
		sourceColumn: context_journal_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column context_journal_rank
		dataType: int64
		formatString: 0
		lineageTag: 2872583f-a481-45ca-943d-39835b8970e6
		summarizeBy: sum
		sourceColumn: context_journal_rank

		annotation SummarizationSetBy = Automatic

	column context_journal_pct
		dataType: int64
		formatString: 0
		lineageTag: 3f42545f-a2d9-46bc-9a9a-29dd0cb2ad47
		summarizeBy: sum
		sourceColumn: context_journal_pct

		annotation SummarizationSetBy = Automatic

	column context_similar_age_mean
		dataType: double
		lineageTag: eec60837-6d25-42cd-b483-9085feaf21a6
		summarizeBy: sum
		sourceColumn: context_similar_age_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column context_similar_age_pct
		dataType: int64
		formatString: 0
		lineageTag: e03f4a65-73f8-4b07-9617-0c5e0b985000
		summarizeBy: sum
		sourceColumn: context_similar_age_pct

		annotation SummarizationSetBy = Automatic

	column count_total
		dataType: int64
		formatString: 0
		lineageTag: bf44ad35-1907-41e4-b2c6-f070cf245695
		summarizeBy: sum
		sourceColumn: count_total

		annotation SummarizationSetBy = Automatic

	column count_twitter
		dataType: int64
		formatString: 0
		lineageTag: e6694eb3-1e54-432b-8668-37d217167a70
		summarizeBy: sum
		sourceColumn: count_twitter

		annotation SummarizationSetBy = Automatic

	column count_news
		dataType: int64
		formatString: 0
		lineageTag: b6fd2c76-9389-4e5d-af24-fba6a73cf761
		summarizeBy: sum
		sourceColumn: count_news

		annotation SummarizationSetBy = Automatic

	column count_blogs
		dataType: int64
		formatString: 0
		lineageTag: 8e881848-d909-4f97-8b33-74b27eade5cf
		summarizeBy: sum
		sourceColumn: count_blogs

		annotation SummarizationSetBy = Automatic

	column count_facebook
		dataType: int64
		formatString: 0
		lineageTag: 3fb7f6f9-1c96-4612-a995-b7f846e7d7fa
		summarizeBy: sum
		sourceColumn: count_facebook

		annotation SummarizationSetBy = Automatic

	column count_reddit
		dataType: int64
		formatString: 0
		lineageTag: 561a6cca-0668-49c3-b713-e192fe7a3260
		summarizeBy: sum
		sourceColumn: count_reddit

		annotation SummarizationSetBy = Automatic

	column count_wikipedia
		dataType: int64
		formatString: 0
		lineageTag: 3aba92a2-728e-429c-a7b2-a072fd6226b1
		summarizeBy: sum
		sourceColumn: count_wikipedia

		annotation SummarizationSetBy = Automatic

	column count_policy
		dataType: int64
		formatString: 0
		lineageTag: 9bc2c09d-b200-4379-bbfa-dcccb80903d7
		summarizeBy: sum
		sourceColumn: count_policy

		annotation SummarizationSetBy = Automatic

	column count_patent
		dataType: int64
		formatString: 0
		lineageTag: d9e92323-9a86-42e8-890e-44f8ec2b7f24
		summarizeBy: sum
		sourceColumn: count_patent

		annotation SummarizationSetBy = Automatic

	column count_video
		dataType: int64
		formatString: 0
		lineageTag: 88a5b3db-8908-41af-a769-e517e59a921d
		summarizeBy: sum
		sourceColumn: count_video

		annotation SummarizationSetBy = Automatic

	column count_mendeley
		dataType: int64
		formatString: 0
		lineageTag: 5ece7240-6e2a-4434-817b-38aac8af64b8
		summarizeBy: sum
		sourceColumn: count_mendeley

		annotation SummarizationSetBy = Automatic

	column cited_by_accounts_count
		dataType: string
		lineageTag: f2db1fbc-349d-42d2-b49f-496de0c894af
		summarizeBy: none
		sourceColumn: cited_by_accounts_count

		annotation SummarizationSetBy = Automatic

	column last_updated
		dataType: string
		lineageTag: b3ebc12f-c2bb-40ed-a42e-05122383c532
		summarizeBy: none
		sourceColumn: last_updated

		annotation SummarizationSetBy = Automatic

	column readers_mendeley
		dataType: int64
		formatString: 0
		lineageTag: 07020fa9-1939-4e5f-8153-fd5f390cfa50
		summarizeBy: sum
		sourceColumn: readers_mendeley

		annotation SummarizationSetBy = Automatic

	column readers_citeulike
		dataType: int64
		formatString: 0
		lineageTag: f1657ef4-f819-46c9-9579-e10bf33a1b67
		summarizeBy: sum
		sourceColumn: readers_citeulike

		annotation SummarizationSetBy = Automatic

	column readers_connotea
		dataType: int64
		formatString: 0
		lineageTag: 507bb196-a2e5-4a4b-9079-095479732e60
		summarizeBy: sum
		sourceColumn: readers_connotea

		annotation SummarizationSetBy = Automatic

	column context_similar_age_journal_mean
		dataType: double
		lineageTag: 60c17a41-9f22-405e-9c0c-82c42d4ced7f
		summarizeBy: sum
		sourceColumn: context_similar_age_journal_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column context_similar_age_journal_pct
		dataType: int64
		formatString: 0
		lineageTag: 15a9f925-d70c-4699-9e42-2f7702a0456e
		summarizeBy: sum
		sourceColumn: context_similar_age_journal_pct

		annotation SummarizationSetBy = Automatic

	column citation_pmc
		dataType: string
		lineageTag: 63f2740d-4568-4134-9c80-004582a7bef5
		summarizeBy: none
		sourceColumn: citation_pmc

		annotation SummarizationSetBy = Automatic

	column citation_arxiv_id
		dataType: string
		lineageTag: 3651fd53-ffef-4351-80d5-cdb991453053
		summarizeBy: none
		sourceColumn: citation_arxiv_id

		annotation SummarizationSetBy = Automatic

	column citation_issns
		dataType: string
		lineageTag: d83785e7-a150-4466-b452-c49fb2950f61
		summarizeBy: none
		sourceColumn: citation_issns

		annotation SummarizationSetBy = Automatic

	column citation_dimensions_publication_id
		dataType: string
		lineageTag: 5da0869a-8d1d-42dc-8391-dcee6262a7e0
		summarizeBy: none
		sourceColumn: citation_dimensions_publication_id

		annotation SummarizationSetBy = Automatic

	column citation_type
		dataType: string
		lineageTag: 7f67f223-b518-45be-9ef8-b64148cafd15
		summarizeBy: none
		sourceColumn: citation_type

		annotation SummarizationSetBy = Automatic

	column citation_epubdate
		dataType: dateTime
		formatString: General Date
		lineageTag: a97f1e69-e3ac-4a02-b578-42e454197298
		summarizeBy: none
		sourceColumn: citation_epubdate

		variation Variation
			isDefault
			relationship: 6f02cf31-9159-4055-99bd-d8d3e290d438
			defaultHierarchy: LocalDateTable_c3b6eebd-7955-4a6f-a984-ef2cd111002d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column citation_pubdate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ed0f900-9f4f-4c51-be85-e6e23c29862d
		summarizeBy: none
		sourceColumn: citation_pubdate

		variation Variation
			isDefault
			relationship: 316d111b-3181-48a8-9f36-4a4c2c303ba5
			defaultHierarchy: LocalDateTable_d048a42a-4ded-4018-b601-e4a05389aa89.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column sentiment_v1_counts
		dataType: string
		lineageTag: 5a4826b7-b787-44d0-b1ab-b5ff976d746a
		summarizeBy: none
		sourceColumn: sentiment_v1_counts

		annotation SummarizationSetBy = Automatic

	column sample_note
		dataType: string
		lineageTag: ff9eb582-8026-4f24-aa6f-fd399077cd64
		summarizeBy: none
		sourceColumn: sample_note

		annotation SummarizationSetBy = Automatic

	partition sd_altmetric = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\impact_workbook (1) (1).xlsx"), null, true),
				    sd_altmetric_Sheet = Source{[Item="sd_altmetric",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(sd_altmetric_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"doi", type text}, {"altmetric_id", Int64.Type}, {"altmetric_publication_date", Int64.Type}, {"journal", type text}, {"cited_by_posts_count", Int64.Type}, {"cited_by_tweeters_count", Int64.Type}, {"cited_by_bluesky_count", Int64.Type}, {"cited_by_msm_count", Int64.Type}, {"cited_by_feeds_count", Int64.Type}, {"cited_by_guidelines_count", Int64.Type}, {"cited_by_patents_count", Int64.Type}, {"n_doc_mentions", Int64.Type}, {"n_sci_mentions", Int64.Type}, {"n_com_mentions", Int64.Type}, {"n_pub_mentions", Int64.Type}, {"n_practitioner_mentions", Int64.Type}, {"n_researcher_mentions", Int64.Type}, {"n_science_communicator_mentions", Int64.Type}, {"n_members_of_public_mentions", Int64.Type}, {"mendeley_readers", Int64.Type}, {"altmetric_score", type number}, {"pmid", Int64.Type}, {"title", type text}, {"score", type number}, {"score_1d", Int64.Type}, {"score_1w", Int64.Type}, {"score_1m", Int64.Type}, {"score_3m", type number}, {"score_6m", type number}, {"score_1y", type number}, {"context_all_mean", type number}, {"context_all_rank", Int64.Type}, {"context_all_pct", Int64.Type}, {"context_journal_mean", type number}, {"context_journal_rank", Int64.Type}, {"context_journal_pct", Int64.Type}, {"context_similar_age_mean", type number}, {"context_similar_age_pct", Int64.Type}, {"count_total", Int64.Type}, {"count_twitter", Int64.Type}, {"count_news", Int64.Type}, {"count_blogs", Int64.Type}, {"count_facebook", Int64.Type}, {"count_reddit", Int64.Type}, {"count_wikipedia", Int64.Type}, {"count_policy", Int64.Type}, {"count_patent", Int64.Type}, {"count_video", Int64.Type}, {"count_mendeley", Int64.Type}, {"cited_by_accounts_count", type any}, {"last_updated", type any}, {"readers_mendeley", Int64.Type}, {"readers_citeulike", Int64.Type}, {"readers_connotea", Int64.Type}, {"context_similar_age_journal_mean", type number}, {"context_similar_age_journal_pct", Int64.Type}, {"citation_pmc", type text}, {"citation_arxiv_id", type any}, {"citation_issns", type text}, {"citation_dimensions_publication_id", type text}, {"citation_type", type text}, {"citation_epubdate", type datetime}, {"citation_pubdate", type datetime}, {"sentiment_v1_counts", type text}, {"sample_note", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

