table _run_summary
	lineageTag: e02377e2-e455-47d8-8add-ea00614946b7

	column metric
		dataType: string
		lineageTag: 41cac401-fd91-491b-baf9-644399b826c1
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		lineageTag: 31ad0491-80af-442e-809f-4dfcc7a34fe8
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	partition _run_summary = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    _run_summary_Sheet = Source{[Item="_run_summary",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(_run_summary_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"metric", type text}, {"value", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

