table di_pub_citing_publication
	lineageTag: 6bcb6718-9833-4ee5-89a5-05c35edae57e

	column citing_dimensions_id
		dataType: string
		lineageTag: 81f6c8e3-5510-41fe-8b8d-f436ad132e12
		summarizeBy: none
		sourceColumn: citing_dimensions_id

		annotation SummarizationSetBy = Automatic

	column citing_doi
		dataType: string
		lineageTag: 45b932f8-49ca-4568-aa4a-67c1074a9796
		summarizeBy: none
		sourceColumn: citing_doi

		annotation SummarizationSetBy = Automatic

	column journal_id
		dataType: string
		lineageTag: 12e68693-e2c4-46f1-b2fb-65fa801f2f3d
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column journal_title
		dataType: string
		lineageTag: 98aaab51-0055-483e-842d-b224706aba6d
		summarizeBy: none
		sourceColumn: journal_title

		annotation SummarizationSetBy = Automatic

	column pub_year
		dataType: int64
		formatString: 0
		lineageTag: 55187882-080b-4bee-8025-8b22f22dafef
		summarizeBy: sum
		sourceColumn: pub_year

		annotation SummarizationSetBy = Automatic

	column document_type
		dataType: string
		lineageTag: 6cbf1db2-5dd0-4151-a93e-216bd4a9ec28
		summarizeBy: none
		sourceColumn: document_type

		annotation SummarizationSetBy = Automatic

	column times_cited
		dataType: int64
		formatString: 0
		lineageTag: 04397f57-b36f-4e1e-ba25-cf0f24a9f46c
		summarizeBy: sum
		sourceColumn: times_cited

		annotation SummarizationSetBy = Automatic

	column field_citation_ratio
		dataType: string
		lineageTag: 40890731-2f44-4180-9f5a-538ae4bb35bd
		summarizeBy: none
		sourceColumn: field_citation_ratio

		annotation SummarizationSetBy = Automatic

	column altmetric_score_citing
		dataType: string
		lineageTag: 425b3d5c-bb1a-463e-a5f7-a2b6d424540d
		summarizeBy: none
		sourceColumn: altmetric_score_citing

		annotation SummarizationSetBy = Automatic

	column original_dimensions_id
		dataType: string
		lineageTag: 0f39b280-9e9c-4432-b956-d2d5b948d373
		summarizeBy: none
		sourceColumn: original_dimensions_id

		annotation SummarizationSetBy = Automatic

	column original_doi
		dataType: string
		lineageTag: aefa9e11-a7d8-4fb5-b50d-0141020e09d0
		summarizeBy: none
		sourceColumn: original_doi

		annotation SummarizationSetBy = Automatic

	partition di_pub_citing_publication = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    di_pub_citing_publication_Sheet = Source{[Item="di_pub_citing_publication",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(di_pub_citing_publication_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"citing_dimensions_id", type text}, {"citing_doi", type text}, {"journal_id", type text}, {"journal_title", type text}, {"pub_year", Int64.Type}, {"document_type", type any}, {"times_cited", Int64.Type}, {"field_citation_ratio", type any}, {"altmetric_score_citing", type any}, {"original_dimensions_id", type text}, {"original_doi", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

