table document_impact
	lineageTag: 6b95e2f5-07f2-4109-9506-44a5436bd335

	measure 'Total Citations' = DISTINCTCOUNT(di_pub_citing_publication[citing_dimensions_id])
		formatString: 0
		lineageTag: b0a13afb-665c-4a02-9625-db1a52c3cc1f

	measure 'Total Publications' = COUNTROWS(document_impact)
		formatString: 0
		lineageTag: bdebbd29-7d55-49b3-a627-4dd8840e5dc9

	measure 'Publications With Citations' =
			
			CALCULATE(
			    DISTINCTCOUNT(di_pub_citing_publication[original_dimensions_id]),
			    di_pub_citing_publication[original_dimensions_id] <> BLANK()
			)
		formatString: 0
		lineageTag: 31767185-5455-4d05-8177-d2809aa1d05e

	measure '% Publications Cited' = DIVIDE([Publications With Citations], [Total Publications])
		lineageTag: d71db789-bbe9-4ec3-87f8-1ae23edf5c22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Recent Citations (Last 2 Yrs)' =
			
			CALCULATE(
			    DISTINCTCOUNT(di_pub_citing_publication[citing_dimensions_id]),
			    di_pub_citing_publication[pub_year] >= YEAR(TODAY()) - 2
			)
		formatString: 0
		lineageTag: 443369e5-211d-4160-a664-b252865908ba

	measure 'Citations Prior 2 Yrs' =
			
			CALCULATE(
			    DISTINCTCOUNT(di_pub_citing_publication[citing_dimensions_id]),
			    di_pub_citing_publication[pub_year] >= YEAR(TODAY()) - 4,
			    di_pub_citing_publication[pub_year] < YEAR(TODAY()) - 2
			)
		formatString: 0
		lineageTag: bcc27007-d617-4be5-bdf3-704608dd1ef6

	measure 'Recent Citations YoY %' = DIVIDE([Recent Citations (Last 2 Yrs)] - [Citations Prior 2 Yrs], [Citations Prior 2 Yrs])
		lineageTag: 3284d5b3-0316-4e12-aaad-644506404eeb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Citations per Publication' =
			
			MEDIANX(
			    VALUES(document_impact[dimensions_id]),
			    CALCULATE(DISTINCTCOUNT(di_pub_citing_publication[citing_dimensions_id]))
			)
		lineageTag: ed4b7524-d684-4f99-80ff-6c455503ebb5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Altmetric Percentile'
		lineageTag: d2dafda7-5f6a-4b28-86a5-7b0ed4c7ce27

		annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":"\nVAR CurrentRank = [Altmetric Rank]\nVAR TotalPubs = [Total Publications]\nRETURN\nDIVIDE(TotalPubs - CurrentRank, TotalPubs - 1)"}

		annotation 277cc1b9-af89-4597-8e15-cacc25c0886b = ```
				A circular dependency was detected: Measure: 'document_impact'[Altmetric Rank], Measure: 'document_impact'[Altmetric Rank].
				
				```

	measure 'Top 5% Publications' =
			
			VAR P95 = PERCENTILEX.INC(ALL(document_impact), document_impact[altmetric_score], 0.95)
			RETURN
			CALCULATE(
			    COUNTROWS(document_impact),
			    document_impact[altmetric_score] >= P95
			)
		formatString: 0
		lineageTag: 3bdfd853-947a-4fe1-a80e-e3bcd1d5b678

	measure 'Publications With Attention' =
			
			CALCULATE(COUNTROWS(document_impact), document_impact[altmetric_score] > 0)
		formatString: 0
		lineageTag: 0dbbdcc0-c037-418e-b68d-ac04c58d2741

	measure 'Altmetric Rank' =
			
			RANKX(
			    ALL(document_impact),
			    document_impact[altmetric_score],
			    DESC
			)
		lineageTag: 17ed52a9-0398-460f-9d50-3331c9a21dca

	measure 'Altmetric Score Display' = ROUND(SUM(document_impact[altmetric_score]), 0)
		lineageTag: 37d38239-7c7a-4777-a9b6-9e49a3054c71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column doi
		dataType: string
		lineageTag: 326c8603-16a6-4ada-b23a-57c62ebdcd62
		summarizeBy: none
		sourceColumn: doi

		annotation SummarizationSetBy = Automatic

	column dimensions_id
		dataType: string
		lineageTag: cbafefb4-f87b-431c-b23f-8483cdae873f
		summarizeBy: none
		sourceColumn: dimensions_id

		annotation SummarizationSetBy = Automatic

	column publication_title
		dataType: string
		lineageTag: 80d51ddc-a49b-40a8-97bf-1217c80f0185
		summarizeBy: none
		sourceColumn: publication_title

		annotation SummarizationSetBy = Automatic

	column target_name
		dataType: string
		lineageTag: 86264f07-f651-4643-aa32-4ad3cb3a0529
		summarizeBy: none
		sourceColumn: target_name

		annotation SummarizationSetBy = Automatic

	column publication_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cf013ecc-8eec-4694-98bb-ba1ac5fba897
		summarizeBy: none
		sourceColumn: publication_date

		variation Variation
			isDefault
			relationship: 1979aaa3-db08-4191-aa28-fe4fb3f8c3a2
			defaultHierarchy: LocalDateTable_64749973-e55b-412c-a81e-88355a75fbce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column publication_year
		dataType: int64
		formatString: 0
		lineageTag: 0f969779-6a80-4482-92a0-8007f4ee3439
		summarizeBy: sum
		sourceColumn: publication_year

		annotation SummarizationSetBy = Automatic

	column total_citation
		dataType: string
		lineageTag: 12939bbe-c5fd-429d-8e6b-07330bbc94dd
		summarizeBy: none
		sourceColumn: total_citation

		annotation SummarizationSetBy = Automatic

	column publication_type
		dataType: string
		lineageTag: 2fb1e987-05cb-4c6e-b04d-7caa94afbe40
		summarizeBy: none
		sourceColumn: publication_type

		annotation SummarizationSetBy = Automatic

	column is_erratum_or_retraction
		dataType: string
		lineageTag: f25021a2-66fe-49f7-b533-b0cba2b399d6
		summarizeBy: none
		sourceColumn: is_erratum_or_retraction

		annotation SummarizationSetBy = Automatic

	column is_open_access
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 998ba976-d39f-44bc-a4c9-44c069a7bc62
		summarizeBy: none
		sourceColumn: is_open_access

		annotation SummarizationSetBy = Automatic

	column open_access_status
		dataType: string
		lineageTag: b21a85fc-61d4-4382-914b-0e00df52c91c
		summarizeBy: none
		sourceColumn: open_access_status

		annotation SummarizationSetBy = Automatic

	column recent_citations
		dataType: string
		lineageTag: 8676b954-2503-4bba-8e7c-97385a034d39
		summarizeBy: none
		sourceColumn: recent_citations

		annotation SummarizationSetBy = Automatic

	column altmetric_id
		dataType: int64
		formatString: 0
		lineageTag: 5b04d3be-7927-4100-854a-f714708dffbe
		summarizeBy: sum
		sourceColumn: altmetric_id

		annotation SummarizationSetBy = Automatic

	column altmetric_score
		dataType: double
		lineageTag: 289a30ac-149d-43ed-9787-5a45735cc659
		summarizeBy: none
		sourceColumn: altmetric_score

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cited_by_posts_count
		dataType: int64
		formatString: 0
		lineageTag: 448b1c57-99b9-4339-bada-3eef7d2b6347
		summarizeBy: sum
		sourceColumn: cited_by_posts_count

		annotation SummarizationSetBy = Automatic

	column cited_by_msm_count
		dataType: int64
		formatString: 0
		lineageTag: 5c44c48c-75e0-4d8a-b4cb-9f159146b70f
		summarizeBy: sum
		sourceColumn: cited_by_msm_count

		annotation SummarizationSetBy = Automatic

	column cited_by_tweeters_count
		dataType: int64
		formatString: 0
		lineageTag: e52321fe-c545-47ba-a9f7-a7ff55bdb51a
		summarizeBy: sum
		sourceColumn: cited_by_tweeters_count

		annotation SummarizationSetBy = Automatic

	column cited_by_bluesky_count
		dataType: int64
		formatString: 0
		lineageTag: eb35bf68-c3d6-4bf2-9649-dfb5b37de111
		summarizeBy: sum
		sourceColumn: cited_by_bluesky_count

		annotation SummarizationSetBy = Automatic

	column cited_by_feeds_count
		dataType: int64
		formatString: 0
		lineageTag: 956d47f1-5d17-42fa-9e15-1f8a15d83bf5
		summarizeBy: sum
		sourceColumn: cited_by_feeds_count

		annotation SummarizationSetBy = Automatic

	column cited_by_guidelines_count
		dataType: int64
		formatString: 0
		lineageTag: c1339fc7-8f0d-4e1b-aa72-414ca33f6d54
		summarizeBy: sum
		sourceColumn: cited_by_guidelines_count

		annotation SummarizationSetBy = Automatic

	column patent_citation
		dataType: int64
		formatString: 0
		lineageTag: 219f94f4-7bd6-4de9-b872-b92e448d073e
		summarizeBy: sum
		sourceColumn: patent_citation

		annotation SummarizationSetBy = Automatic

	column n_doc_mentions
		dataType: int64
		formatString: 0
		lineageTag: a24a018f-440c-41d1-9adc-de95b5131c55
		summarizeBy: sum
		sourceColumn: n_doc_mentions

		annotation SummarizationSetBy = Automatic

	column n_sci_mentions
		dataType: int64
		formatString: 0
		lineageTag: 4918773a-20f5-4f9d-852a-6c32870a51d9
		summarizeBy: sum
		sourceColumn: n_sci_mentions

		annotation SummarizationSetBy = Automatic

	column n_com_mentions
		dataType: int64
		formatString: 0
		lineageTag: 96aa929c-40da-4478-b159-889f3b54d9cf
		summarizeBy: sum
		sourceColumn: n_com_mentions

		annotation SummarizationSetBy = Automatic

	column n_pub_mentions
		dataType: int64
		formatString: 0
		lineageTag: 9c8aa391-5523-4b74-8681-c562a6a3610a
		summarizeBy: sum
		sourceColumn: n_pub_mentions

		annotation SummarizationSetBy = Automatic

	column mendeley_readers
		dataType: int64
		formatString: 0
		lineageTag: 7b961ed7-50e1-4e51-9b3c-02c2ff3906f3
		summarizeBy: sum
		sourceColumn: mendeley_readers

		annotation SummarizationSetBy = Automatic

	column altmetric_publication_date
		dataType: int64
		formatString: 0
		lineageTag: e628d8b9-4e98-4327-b9e2-58665e026242
		summarizeBy: sum
		sourceColumn: altmetric_publication_date

		annotation SummarizationSetBy = Automatic

	column sentiment_strong_neg
		dataType: int64
		formatString: 0
		lineageTag: 1fdb2d1d-292b-4424-9389-ae2da9254e99
		summarizeBy: sum
		sourceColumn: sentiment_strong_neg

		annotation SummarizationSetBy = Automatic

	column sentiment_neg
		dataType: int64
		formatString: 0
		lineageTag: bfb3184c-01b2-41eb-8aad-043e5219c13d
		summarizeBy: sum
		sourceColumn: sentiment_neg

		annotation SummarizationSetBy = Automatic

	column sentiment_neutral_neg
		dataType: int64
		formatString: 0
		lineageTag: 2a813d7a-1349-4036-9aa7-020cffa47f6b
		summarizeBy: sum
		sourceColumn: sentiment_neutral_neg

		annotation SummarizationSetBy = Automatic

	column sentiment_neutral
		dataType: int64
		formatString: 0
		lineageTag: bb03e1c0-2d0d-440f-9c5d-d839e2a0d91d
		summarizeBy: sum
		sourceColumn: sentiment_neutral

		annotation SummarizationSetBy = Automatic

	column sentiment_neutral_pos
		dataType: int64
		formatString: 0
		lineageTag: 0dd93d30-02d9-45df-b17d-8d5acb01f5bc
		summarizeBy: sum
		sourceColumn: sentiment_neutral_pos

		annotation SummarizationSetBy = Automatic

	column sentiment_pos
		dataType: int64
		formatString: 0
		lineageTag: 4a6ace41-edde-49b0-b639-e362208c87d2
		summarizeBy: sum
		sourceColumn: sentiment_pos

		annotation SummarizationSetBy = Automatic

	column sentiment_strong_pos
		dataType: int64
		formatString: 0
		lineageTag: 02346ec0-db0d-450a-824d-a05d1a701748
		summarizeBy: sum
		sourceColumn: sentiment_strong_pos

		annotation SummarizationSetBy = Automatic

	column journal_id
		dataType: string
		lineageTag: 331b07b5-4c7f-4b34-9964-57efe2901218
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column arxiv_id
		dataType: string
		lineageTag: 694e605f-c410-4e56-9153-7d8c12cf534c
		summarizeBy: none
		sourceColumn: arxiv_id

		annotation SummarizationSetBy = Automatic

	column abstract
		dataType: string
		lineageTag: 829353fb-cb41-416c-8467-a14a52ae6cab
		summarizeBy: none
		sourceColumn: abstract

		annotation SummarizationSetBy = Automatic

	column author_names
		dataType: string
		lineageTag: e8842498-99d9-41d7-bc84-d732afd84271
		summarizeBy: none
		sourceColumn: author_names

		annotation SummarizationSetBy = Automatic

	column corresponding_author
		dataType: string
		lineageTag: 4fd6fb6a-ab9c-45e7-8ec5-31e2317e67c6
		summarizeBy: none
		sourceColumn: corresponding_author

		annotation SummarizationSetBy = Automatic

	column orcid_list
		dataType: string
		lineageTag: bb1ceeba-4d3a-4d26-9859-c4c0cee1f746
		summarizeBy: none
		sourceColumn: orcid_list

		annotation SummarizationSetBy = Automatic

	column authors_affiliation
		dataType: string
		lineageTag: f236a07b-f286-4bcb-904a-503abf0ce8d7
		summarizeBy: none
		sourceColumn: authors_affiliation

		annotation SummarizationSetBy = Automatic

	column field_citation_ratio
		dataType: string
		lineageTag: 734b4b0e-ab62-4cd1-8b5e-fec8ee8e6998
		summarizeBy: none
		sourceColumn: field_citation_ratio

		annotation SummarizationSetBy = Automatic

	column relative_citation_ratio
		dataType: string
		lineageTag: 164031d0-482d-4957-8fd0-87f0b759f802
		summarizeBy: none
		sourceColumn: relative_citation_ratio

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 4c031e40-3703-4e20-8ec4-6d527501b48e
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column linkout
		dataType: string
		lineageTag: 654afaf9-a9ef-4fd6-a496-6070ee7fac87
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column mesh_terms
		dataType: string
		lineageTag: d763bdf8-a3c7-414c-a589-113502029957
		summarizeBy: none
		sourceColumn: mesh_terms

		annotation SummarizationSetBy = Automatic

	column funders_name
		dataType: string
		lineageTag: 79b48fc3-37f3-4762-bc32-96ef18e1ac4c
		summarizeBy: none
		sourceColumn: funders_name

		annotation SummarizationSetBy = Automatic

	column disease_area_proxy
		dataType: string
		lineageTag: 3190601b-0fe5-4dcd-a334-cddf66a04d46
		summarizeBy: none
		sourceColumn: disease_area_proxy

		annotation SummarizationSetBy = Automatic

	column source_origin
		dataType: string
		lineageTag: 9b1db3a7-e499-46f7-867c-e1932a04cdac
		summarizeBy: none
		sourceColumn: source_origin

		annotation SummarizationSetBy = Automatic

	column source_origin_keyword
		dataType: string
		lineageTag: ebf893e9-b951-44e5-977d-93e0d74d4011
		summarizeBy: none
		sourceColumn: source_origin_keyword

		annotation SummarizationSetBy = Automatic

	column source_origin_doi
		dataType: string
		lineageTag: 4bef5817-28f3-43fd-a4ef-4414ff203342
		summarizeBy: none
		sourceColumn: source_origin_doi

		annotation SummarizationSetBy = Automatic

	column acknowledgements
		dataType: string
		lineageTag: 9c0f3d9b-5b70-4f07-a684-abb3cc8ea808
		summarizeBy: none
		sourceColumn: acknowledgements

		annotation SummarizationSetBy = Automatic

	column authors_count
		dataType: string
		lineageTag: 9e6a20ab-742c-4e90-ac2e-791283cdd315
		summarizeBy: none
		sourceColumn: authors_count

		annotation SummarizationSetBy = Automatic

	column book_doi
		dataType: string
		lineageTag: 53a5867b-2729-4503-b7e7-b115dcc913be
		summarizeBy: none
		sourceColumn: book_doi

		annotation SummarizationSetBy = Automatic

	column book_series_title
		dataType: string
		lineageTag: bcf6f7c2-5e42-4317-9136-1dd869b30649
		summarizeBy: none
		sourceColumn: book_series_title

		annotation SummarizationSetBy = Automatic

	column book_title
		dataType: string
		lineageTag: 41ca710f-a75d-4301-9c8c-22f1c8d3961d
		summarizeBy: none
		sourceColumn: book_title

		annotation SummarizationSetBy = Automatic

	column category_bra
		dataType: string
		lineageTag: de92f142-b58c-497b-9694-98d8e9853a0e
		summarizeBy: none
		sourceColumn: category_bra

		annotation SummarizationSetBy = Automatic

	column category_for
		dataType: string
		lineageTag: f8ca112c-df00-455e-b3ed-8df282feea28
		summarizeBy: none
		sourceColumn: category_for

		annotation SummarizationSetBy = Automatic

	column category_for_2020
		dataType: string
		lineageTag: 9a609045-8d08-4e92-ad30-49dc4713bdb1
		summarizeBy: none
		sourceColumn: category_for_2020

		annotation SummarizationSetBy = Automatic

	column category_hrcs_hc
		dataType: string
		lineageTag: 6167c783-9056-4a30-ad31-24f8b48ffb0c
		summarizeBy: none
		sourceColumn: category_hrcs_hc

		annotation SummarizationSetBy = Automatic

	column category_hrcs_rac
		dataType: string
		lineageTag: 6cce674d-a9ff-4d29-a162-ae3c3520f793
		summarizeBy: none
		sourceColumn: category_hrcs_rac

		annotation SummarizationSetBy = Automatic

	column category_icrp_cso
		dataType: string
		lineageTag: 0894d72a-a39e-4151-9ead-88b22c7af420
		summarizeBy: none
		sourceColumn: category_icrp_cso

		annotation SummarizationSetBy = Automatic

	column category_icrp_ct
		dataType: string
		lineageTag: 123163f2-b14b-4282-9ba7-ed159ce45c10
		summarizeBy: none
		sourceColumn: category_icrp_ct

		annotation SummarizationSetBy = Automatic

	column category_rcdc
		dataType: string
		lineageTag: da5ba40a-e6f2-472e-9f22-2277510c0e9c
		summarizeBy: none
		sourceColumn: category_rcdc

		annotation SummarizationSetBy = Automatic

	column category_sdg
		dataType: string
		lineageTag: 4f336045-9202-41d5-8bc6-590c16e61acc
		summarizeBy: none
		sourceColumn: category_sdg

		annotation SummarizationSetBy = Automatic

	column category_uoa
		dataType: string
		lineageTag: a38417cd-4067-44af-a9f1-420d532bc8e5
		summarizeBy: none
		sourceColumn: category_uoa

		annotation SummarizationSetBy = Automatic

	column clinical_trial_ids
		dataType: string
		lineageTag: f92cafe4-1859-4a81-aff8-e22a8f10e4d5
		summarizeBy: none
		sourceColumn: clinical_trial_ids

		annotation SummarizationSetBy = Automatic

	column concepts
		dataType: string
		lineageTag: bea7650b-06cb-4ec2-b004-ffa582881637
		summarizeBy: none
		sourceColumn: concepts

		annotation SummarizationSetBy = Automatic

	column concepts_relevant
		dataType: string
		lineageTag: adf0807d-6cf3-4692-a8df-bf11b82fba8e
		summarizeBy: none
		sourceColumn: concepts_relevant

		annotation SummarizationSetBy = Automatic

	column concepts_scores
		dataType: string
		lineageTag: e5255bdf-8f7a-49c4-9c02-52a5b4486acf
		summarizeBy: none
		sourceColumn: concepts_scores

		annotation SummarizationSetBy = Automatic

	column date_inserted
		dataType: string
		lineageTag: ebaab64f-bcb0-481a-8e9f-47de7b3be593
		summarizeBy: none
		sourceColumn: date_inserted

		annotation SummarizationSetBy = Automatic

	column date_online
		dataType: string
		lineageTag: b9e73437-a6f9-45cb-8977-58921ecda68e
		summarizeBy: none
		sourceColumn: date_online

		annotation SummarizationSetBy = Automatic

	column date_print
		dataType: string
		lineageTag: d78d5c32-e910-4796-acda-a07d0e0acb8a
		summarizeBy: none
		sourceColumn: date_print

		annotation SummarizationSetBy = Automatic

	column editors
		dataType: string
		lineageTag: cdeff8b4-5f7a-4bd3-bf9a-be7ada2641c1
		summarizeBy: none
		sourceColumn: editors

		annotation SummarizationSetBy = Automatic

	column funder_countries
		dataType: string
		lineageTag: 3a2f5bde-81db-4ca8-96a9-5eb782788f84
		summarizeBy: none
		sourceColumn: funder_countries

		annotation SummarizationSetBy = Automatic

	column funding_section
		dataType: string
		lineageTag: 18cc643b-3747-48df-bd85-717f97e1e9cc
		summarizeBy: none
		sourceColumn: funding_section

		annotation SummarizationSetBy = Automatic

	column isbn
		dataType: string
		lineageTag: 2f87b6c6-e39c-46be-9851-98a9a08d4dbd
		summarizeBy: none
		sourceColumn: isbn

		annotation SummarizationSetBy = Automatic

	column issn
		dataType: string
		lineageTag: b9c12b1b-0788-4d03-800f-44e25d544217
		summarizeBy: none
		sourceColumn: issn

		annotation SummarizationSetBy = Automatic

	column issue
		dataType: string
		lineageTag: 25f26401-50e7-4627-be45-b7bccb7b19d3
		summarizeBy: none
		sourceColumn: issue

		annotation SummarizationSetBy = Automatic

	column journal_lists
		dataType: string
		lineageTag: e1e0807a-c920-4c1f-bcd0-3ad878562312
		summarizeBy: none
		sourceColumn: journal_lists

		annotation SummarizationSetBy = Automatic

	column journal_title_raw
		dataType: string
		lineageTag: 2f641325-2be7-4a1e-b7f5-a51997dd19d6
		summarizeBy: none
		sourceColumn: journal_title_raw

		annotation SummarizationSetBy = Automatic

	column open_access
		dataType: string
		lineageTag: 8b31f5f5-fcc1-497f-8d18-8cab95bccf04
		summarizeBy: none
		sourceColumn: open_access

		annotation SummarizationSetBy = Automatic

	column pages
		dataType: string
		lineageTag: fef7b60d-2873-43ed-8dd7-703c6055cc52
		summarizeBy: none
		sourceColumn: pages

		annotation SummarizationSetBy = Automatic

	column pmcid
		dataType: string
		lineageTag: adc320dd-c288-4b2b-8b29-cf2092b8d47f
		summarizeBy: none
		sourceColumn: pmcid

		annotation SummarizationSetBy = Automatic

	column pmid
		dataType: int64
		formatString: 0
		lineageTag: 08b3268d-c9f3-4999-8741-4f25a8770396
		summarizeBy: sum
		sourceColumn: pmid

		annotation SummarizationSetBy = Automatic

	column proceedings_title
		dataType: string
		lineageTag: f5dd96f0-8c4b-4f45-ac29-8873fecbb312
		summarizeBy: none
		sourceColumn: proceedings_title

		annotation SummarizationSetBy = Automatic

	column publisher
		dataType: string
		lineageTag: 17c48799-f5c9-474b-bd5b-0c469ae0df67
		summarizeBy: none
		sourceColumn: publisher

		annotation SummarizationSetBy = Automatic

	column referenced_pubs
		dataType: string
		lineageTag: 3f2ac1bf-395a-41ea-a37d-b2186894406e
		summarizeBy: none
		sourceColumn: referenced_pubs

		annotation SummarizationSetBy = Automatic

	column research_org_cities
		dataType: string
		lineageTag: 2f4a996d-4baf-467f-95ee-fcae2e8e49e1
		summarizeBy: none
		sourceColumn: research_org_cities

		annotation SummarizationSetBy = Automatic

	column research_org_countries
		dataType: string
		lineageTag: 2bcb4c2c-5a22-49ac-8e50-12d2d09cc3bb
		summarizeBy: none
		sourceColumn: research_org_countries

		annotation SummarizationSetBy = Automatic

	column research_org_state_codes
		dataType: string
		lineageTag: a218b824-8f5a-42da-b6e5-9ec75eb9cfe0
		summarizeBy: none
		sourceColumn: research_org_state_codes

		annotation SummarizationSetBy = Automatic

	column research_org_types
		dataType: string
		lineageTag: c0730601-631d-4ea9-b415-2cc8ccf2df9c
		summarizeBy: none
		sourceColumn: research_org_types

		annotation SummarizationSetBy = Automatic

	column resulting_publication_doi
		dataType: string
		lineageTag: 2497f5f6-4d6d-4037-84c7-858e14bdc706
		summarizeBy: none
		sourceColumn: resulting_publication_doi

		annotation SummarizationSetBy = Automatic

	column relevance_score
		dataType: string
		lineageTag: 2aaf21cd-a82f-48e6-9fff-a1e88642354d
		summarizeBy: none
		sourceColumn: relevance_score

		annotation SummarizationSetBy = Automatic

	column source_title
		dataType: string
		lineageTag: 0623ff74-56dd-43e7-b701-8ea00ed1a26b
		summarizeBy: none
		sourceColumn: source_title

		annotation SummarizationSetBy = Automatic

	column subtitles
		dataType: string
		lineageTag: 37ce5876-eae0-4a1c-9a20-e72369121e91
		summarizeBy: none
		sourceColumn: subtitles

		annotation SummarizationSetBy = Automatic

	column supporting_grant_ids
		dataType: string
		lineageTag: ab3988b7-77a8-4bbd-8e44-f5a749a0c1ff
		summarizeBy: none
		sourceColumn: supporting_grant_ids

		annotation SummarizationSetBy = Automatic

	column volume
		dataType: int64
		formatString: 0
		lineageTag: 4634054a-9f30-4ddf-b14f-f61496f58f85
		summarizeBy: sum
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

	column sample_note
		dataType: string
		lineageTag: 6c8852a3-662f-4675-8ec4-75becec65604
		summarizeBy: none
		sourceColumn: sample_note

		annotation SummarizationSetBy = Automatic

	column Column
		type: calculated
		lineageTag: aa710b14-c201-4c70-b4f7-4807a7bffdff
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	column 'Publication Display' =
			
			document_impact[publication_title] & UNICHAR(10) &  document_impact[publication_year]
		lineageTag: bc0d91ff-eb35-48f2-ba4e-a791b80c9420
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Attention Quadrant' =
			
			VAR MedCitations = MEDIANX(ALL(document_impact), [Total Citations])
			VAR MedAltmetric = MEDIANX(ALL(document_impact), document_impact[altmetric_score])
			VAR CurrentCitations = [Total Citations]
			VAR CurrentAltmetric = document_impact[altmetric_score]
			RETURN
			SWITCH(
			    TRUE(),
			    CurrentCitations >= MedCitations && CurrentAltmetric >= MedAltmetric, "Amplify",
			    CurrentAltmetric >= MedAltmetric, "Attention-led",
			    CurrentCitations >= MedCitations, "Quiet but cited",
			    "Low signal"
			)
		lineageTag: 1bf5afc9-dd19-42df-94e7-da38aa61b9c0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'OA Status Clean' =
			
			SWITCH(
			    document_impact[open_access_status],
			    "oa_all|gold", "Gold",
			    "oa_all|hybrid", "Hybrid",
			    "oa_all|bronze", "Bronze",
			    "oa_all|green", "Green",
			    "closed", "Closed",
			    document_impact[open_access_status]
			)
		lineageTag: 7b287774-d828-4f16-8c73-1e752d7eb6d7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition document_impact = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    document_impact_Sheet = Source{[Item="document_impact",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(document_impact_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"doi", type text}, {"dimensions_id", type text}, {"publication_title", type text}, {"target_name", type text}, {"publication_date", type date}, {"publication_year", Int64.Type}, {"total_citation", type any}, {"publication_type", type text}, {"is_erratum_or_retraction", type any}, {"is_open_access", type logical}, {"open_access_status", type text}, {"recent_citations", type any}, {"altmetric_id", Int64.Type}, {"altmetric_score", type number}, {"cited_by_posts_count", Int64.Type}, {"cited_by_msm_count", Int64.Type}, {"cited_by_tweeters_count", Int64.Type}, {"cited_by_bluesky_count", Int64.Type}, {"cited_by_feeds_count", Int64.Type}, {"cited_by_guidelines_count", Int64.Type}, {"patent_citation", Int64.Type}, {"n_doc_mentions", Int64.Type}, {"n_sci_mentions", Int64.Type}, {"n_com_mentions", Int64.Type}, {"n_pub_mentions", Int64.Type}, {"mendeley_readers", Int64.Type}, {"altmetric_publication_date", Int64.Type}, {"sentiment_strong_neg", Int64.Type}, {"sentiment_neg", Int64.Type}, {"sentiment_neutral_neg", Int64.Type}, {"sentiment_neutral", Int64.Type}, {"sentiment_neutral_pos", Int64.Type}, {"sentiment_pos", Int64.Type}, {"sentiment_strong_pos", Int64.Type}, {"journal_id", type text}, {"arxiv_id", type any}, {"abstract", type text}, {"author_names", type text}, {"corresponding_author", type any}, {"orcid_list", type any}, {"authors_affiliation", type text}, {"field_citation_ratio", type any}, {"relative_citation_ratio", type any}, {"dimensions_url", type text}, {"linkout", type text}, {"mesh_terms", type text}, {"funders_name", type text}, {"disease_area_proxy", type any}, {"source_origin", type text}, {"source_origin_keyword", type any}, {"source_origin_doi", type text}, {"acknowledgements", type any}, {"authors_count", type any}, {"book_doi", type any}, {"book_series_title", type any}, {"book_title", type any}, {"category_bra", type text}, {"category_for", type text}, {"category_for_2020", type any}, {"category_hrcs_hc", type text}, {"category_hrcs_rac", type text}, {"category_icrp_cso", type text}, {"category_icrp_ct", type text}, {"category_rcdc", type text}, {"category_sdg", type text}, {"category_uoa", type text}, {"clinical_trial_ids", type any}, {"concepts", type any}, {"concepts_relevant", type any}, {"concepts_scores", type any}, {"date_inserted", type any}, {"date_online", type any}, {"date_print", type any}, {"editors", type any}, {"funder_countries", type any}, {"funding_section", type any}, {"isbn", type any}, {"issn", type any}, {"issue", type text}, {"journal_lists", type text}, {"journal_title_raw", type text}, {"open_access", type text}, {"pages", type text}, {"pmcid", type text}, {"pmid", Int64.Type}, {"proceedings_title", type any}, {"publisher", type any}, {"referenced_pubs", type any}, {"research_org_cities", type text}, {"research_org_countries", type text}, {"research_org_state_codes", type text}, {"research_org_types", type any}, {"resulting_publication_doi", type any}, {"relevance_score", type any}, {"source_title", type any}, {"subtitles", type any}, {"supporting_grant_ids", type any}, {"volume", Int64.Type}, {"sample_note", type any}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"doi"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates", {"dimensions_id"}),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Duplicates1", {"dimensions_id"})
				in
				    #"Removed Duplicates2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

