table enr_journal_stats
	lineageTag: 0d09e751-7f72-47ae-be9d-a9e128ffbe9b

	column journal_id
		dataType: string
		lineageTag: 3f84d6fd-9a97-4e41-a868-d0b0ace897c7
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column journal_title
		dataType: string
		lineageTag: 17ac3592-4b3f-448d-a130-498ebc2ed45d
		summarizeBy: none
		sourceColumn: journal_title

		annotation SummarizationSetBy = Automatic

	column publisher_country
		dataType: string
		lineageTag: db9e286f-05b9-4ba6-a152-dce58f554acb
		summarizeBy: none
		sourceColumn: publisher_country

		annotation SummarizationSetBy = Automatic

	column category_hra
		dataType: string
		lineageTag: 0e0b8038-9b5b-4673-b7b5-56228f4e93c3
		summarizeBy: none
		sourceColumn: category_hra

		annotation SummarizationSetBy = Automatic

	column citations_total
		dataType: int64
		formatString: 0
		lineageTag: 54204637-1777-42c1-92a4-f8cecf6ca226
		summarizeBy: sum
		sourceColumn: citations_total

		annotation SummarizationSetBy = Automatic

	column paper_count
		dataType: int64
		formatString: 0
		lineageTag: 536beb2f-08d9-4a82-b6b7-ac20403c5c20
		summarizeBy: sum
		sourceColumn: paper_count

		annotation SummarizationSetBy = Automatic

	column journal_avg_citation
		dataType: string
		lineageTag: ba2db07e-cb04-4a47-826c-44b056dda0ee
		summarizeBy: none
		sourceColumn: journal_avg_citation

		annotation SummarizationSetBy = Automatic

	column is_generalist
		dataType: string
		lineageTag: 23f63744-47a8-4e97-a5a9-24ad04a2442a
		summarizeBy: none
		sourceColumn: is_generalist

		annotation SummarizationSetBy = Automatic

	column enr_loaded_at
		dataType: string
		lineageTag: 09ddbb10-cc76-4ac5-a1a8-773b42719db7
		summarizeBy: none
		sourceColumn: enr_loaded_at

		annotation SummarizationSetBy = Automatic

	partition enr_journal_stats = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    enr_journal_stats_Sheet = Source{[Item="enr_journal_stats",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(enr_journal_stats_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"journal_id", type text}, {"journal_title", type text}, {"publisher_country", type any}, {"category_hra", type any}, {"citations_total", Int64.Type}, {"paper_count", Int64.Type}, {"journal_avg_citation", type any}, {"is_generalist", type any}, {"enr_loaded_at", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

