table enr_pub_citing_pub_link
	lineageTag: 7968c0c0-dccd-436f-bf01-bb06031b3131

	column citing_dimensions_id
		dataType: string
		lineageTag: ba379942-d016-4f54-bb06-f2f7460ceb97
		summarizeBy: none
		sourceColumn: citing_dimensions_id

		annotation SummarizationSetBy = Automatic

	column original_dimensions_id
		dataType: string
		lineageTag: 35cb7add-ca27-41be-b923-92f86c69c198
		summarizeBy: none
		sourceColumn: original_dimensions_id

		annotation SummarizationSetBy = Automatic

	column enr_loaded_at
		dataType: string
		lineageTag: 833211f5-8847-4d8d-aaad-c13f4169f5a3
		summarizeBy: none
		sourceColumn: enr_loaded_at

		annotation SummarizationSetBy = Automatic

	partition enr_pub_citing_pub_link = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    enr_pub_citing_pub_link_Sheet = Source{[Item="enr_pub_citing_pub_link",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(enr_pub_citing_pub_link_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"citing_dimensions_id", type text}, {"original_dimensions_id", type text}, {"enr_loaded_at", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

