table raw_clinical_trial
	lineageTag: a18d4582-36ba-4e57-bc1c-aeccff53311c

	column Column1
		dataType: string
		lineageTag: 7eacad65-5a8a-46f4-a3b2-58a93c3c9fc1
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 68095136-4e90-45bf-804e-c216fc2bd254
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 67e9371d-df90-4fc0-ba63-c42b32bef22a
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition raw_clinical_trial = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    raw_clinical_trial_Sheet = Source{[Item="raw_clinical_trial",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(raw_clinical_trial_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

