table raw_gsk_org_lookup
	lineageTag: f7afc219-be57-4392-bddf-c8638311d1ef

	column Column1
		dataType: string
		lineageTag: 80b1423c-cfaf-42f2-a8b1-67de80d74186
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: fd188b65-1c0a-44d6-90c3-c559acd6e889
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 71d06b38-a95e-4faa-b883-55f002dc1df4
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition raw_gsk_org_lookup = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    raw_gsk_org_lookup_Sheet = Source{[Item="raw_gsk_org_lookup",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(raw_gsk_org_lookup_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

