table raw_journal_stats
	lineageTag: 2b9ad6c7-df24-42b2-a090-6a801cbd3e29

	column journal_id
		dataType: string
		lineageTag: 5f42bb3d-f5ac-4645-b700-e59ca9e90894
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column journal_title
		dataType: string
		lineageTag: 861554f3-38b3-44ea-b8ac-d6ad4690c3d3
		summarizeBy: none
		sourceColumn: journal_title

		annotation SummarizationSetBy = Automatic

	column publisher_country
		dataType: string
		lineageTag: 6f9226ef-fe1a-48a4-8c22-b100567829b9
		summarizeBy: none
		sourceColumn: publisher_country

		annotation SummarizationSetBy = Automatic

	column category_hra
		dataType: string
		lineageTag: bb2d5f3b-91da-4e45-9e78-f4bd17157f42
		summarizeBy: none
		sourceColumn: category_hra

		annotation SummarizationSetBy = Automatic

	column citations_total
		dataType: int64
		formatString: 0
		lineageTag: f7e3ced8-5b7a-4f08-b925-9a4fb22bf8b5
		summarizeBy: sum
		sourceColumn: citations_total

		annotation SummarizationSetBy = Automatic

	column paper_count
		dataType: int64
		formatString: 0
		lineageTag: 8c06fef1-594a-426f-b02f-6359dba14b1a
		summarizeBy: sum
		sourceColumn: paper_count

		annotation SummarizationSetBy = Automatic

	partition raw_journal_stats = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    raw_journal_stats_Sheet = Source{[Item="raw_journal_stats",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_journal_stats_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"journal_id", type text}, {"journal_title", type text}, {"publisher_country", type any}, {"category_hra", type any}, {"citations_total", Int64.Type}, {"paper_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

