table raw_research_organization
	lineageTag: c43041a6-d6e9-476f-8973-812e1063187f

	column source_dimensions_id
		dataType: string
		lineageTag: d1aaf8e1-4317-4fc5-a532-8d7b814edea9
		summarizeBy: none
		sourceColumn: source_dimensions_id

		annotation SummarizationSetBy = Automatic

	column org_grid_id
		dataType: string
		lineageTag: 9fb5c5c6-2b47-40fa-a56a-2559a209b176
		summarizeBy: none
		sourceColumn: org_grid_id

		annotation SummarizationSetBy = Automatic

	column org_name
		dataType: string
		lineageTag: f2b3bc83-602e-4310-94c0-a3af68dc3a5a
		summarizeBy: none
		sourceColumn: org_name

		annotation SummarizationSetBy = Automatic

	column acronyms
		dataType: string
		lineageTag: 4d4f79e8-4836-4754-af76-c29104709385
		summarizeBy: none
		sourceColumn: acronyms

		annotation SummarizationSetBy = Automatic

	column city_name
		dataType: string
		lineageTag: 6cf61c47-edb5-4ce9-854e-8ff95d5d803b
		summarizeBy: none
		sourceColumn: city_name

		annotation SummarizationSetBy = Automatic

	column cnrs_ids
		dataType: string
		lineageTag: 5b48556d-05cf-447b-b7a0-1b27c24cad7f
		summarizeBy: none
		sourceColumn: cnrs_ids

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: edeb6a28-01cb-4d27-92ff-47e915ca0c12
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: 39c71739-438c-4288-b031-5ca41891eda5
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 9a7f0516-bf2c-414d-add8-36ae152dfbf4
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column established
		dataType: int64
		formatString: 0
		lineageTag: 6a33a25b-7d59-4113-9c9f-16ab8c115c3c
		summarizeBy: sum
		sourceColumn: established

		annotation SummarizationSetBy = Automatic

	column external_ids_fundref
		dataType: string
		lineageTag: 0ff99fc2-0a68-4f73-b477-65d73fd573b3
		summarizeBy: none
		sourceColumn: external_ids_fundref

		annotation SummarizationSetBy = Automatic

	column hesa_ids
		dataType: int64
		formatString: 0
		lineageTag: ac6393fd-d570-4b78-94a7-216590e54632
		summarizeBy: sum
		sourceColumn: hesa_ids

		annotation SummarizationSetBy = Automatic

	column hierarchy_details
		dataType: string
		lineageTag: 4bd82d03-bff8-4db9-9da5-4a94956f487f
		summarizeBy: none
		sourceColumn: hierarchy_details

		annotation SummarizationSetBy = Automatic

	column isni_ids
		dataType: string
		lineageTag: 9a871a32-c275-452b-b766-e01d18a559b4
		summarizeBy: none
		sourceColumn: isni_ids

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 345f45cb-8655-445d-9aa2-5efaad336ab0
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column linkout
		dataType: string
		lineageTag: 5b319e08-5670-4365-837b-3d333df4beaf
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		lineageTag: 068b1f18-dd31-47ba-8c10-d0d6eabdae5f
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nuts_level1_code
		dataType: string
		lineageTag: 75ea2d81-79ed-441f-a9ed-6e21ed0d48a6
		summarizeBy: none
		sourceColumn: nuts_level1_code

		annotation SummarizationSetBy = Automatic

	column nuts_level1_name
		dataType: string
		lineageTag: 3c6bffb7-58d4-4523-9c06-3e5406ef5f69
		summarizeBy: none
		sourceColumn: nuts_level1_name

		annotation SummarizationSetBy = Automatic

	column nuts_level2_code
		dataType: string
		lineageTag: d59c6984-d627-4247-87ca-960f523924c3
		summarizeBy: none
		sourceColumn: nuts_level2_code

		annotation SummarizationSetBy = Automatic

	column nuts_level2_name
		dataType: string
		lineageTag: 40feb9e9-b0f9-4dbf-b80d-6467f245de59
		summarizeBy: none
		sourceColumn: nuts_level2_name

		annotation SummarizationSetBy = Automatic

	column nuts_level3_code
		dataType: string
		lineageTag: dc275e7f-8ac4-4ced-92d6-84ebac3445dd
		summarizeBy: none
		sourceColumn: nuts_level3_code

		annotation SummarizationSetBy = Automatic

	column nuts_level3_name
		dataType: string
		lineageTag: db421c7f-a53b-4f07-b20d-54cfe8cf7a75
		summarizeBy: none
		sourceColumn: nuts_level3_name

		annotation SummarizationSetBy = Automatic

	column organization_child_ids
		dataType: string
		lineageTag: b8bea54e-f3cd-4e4d-aa89-30ec66b5bd26
		summarizeBy: none
		sourceColumn: organization_child_ids

		annotation SummarizationSetBy = Automatic

	column organization_parent_ids
		dataType: string
		lineageTag: b9026805-f56d-49a7-8e8e-2ebbe7af1feb
		summarizeBy: none
		sourceColumn: organization_parent_ids

		annotation SummarizationSetBy = Automatic

	column organization_related_ids
		dataType: string
		lineageTag: 2d1b9bcc-cbb9-4b98-8fef-c562b6eb37b3
		summarizeBy: none
		sourceColumn: organization_related_ids

		annotation SummarizationSetBy = Automatic

	column orgref_ids
		dataType: string
		lineageTag: 9e0e29f6-1a44-45cf-8c79-73f3b268fbdf
		summarizeBy: none
		sourceColumn: orgref_ids

		annotation SummarizationSetBy = Automatic

	column redirect
		dataType: string
		lineageTag: 3ef466bf-2167-4fa5-a40a-9a803560a9ce
		summarizeBy: none
		sourceColumn: redirect

		annotation SummarizationSetBy = Automatic

	column ror_ids
		dataType: string
		lineageTag: e1b79150-2821-4bac-89b0-ce6c9436381d
		summarizeBy: none
		sourceColumn: ror_ids

		annotation SummarizationSetBy = Automatic

	column state_name
		dataType: string
		lineageTag: 49753e04-a04c-4205-bdd1-7a7bee8935d0
		summarizeBy: none
		sourceColumn: state_name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 66606949-c822-4ada-95f6-0de05d6fb0a0
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column types
		dataType: string
		lineageTag: fddae93f-ca05-4bcb-a44b-d56abbbd065c
		summarizeBy: none
		sourceColumn: types

		annotation SummarizationSetBy = Automatic

	column ucas_ids
		dataType: string
		lineageTag: 1460a130-a895-49c8-b790-1b850625b024
		summarizeBy: none
		sourceColumn: ucas_ids

		annotation SummarizationSetBy = Automatic

	column ukprn_ids
		dataType: string
		lineageTag: c697d0d7-45c5-4ef2-92fd-78a411ac8dcf
		summarizeBy: none
		sourceColumn: ukprn_ids

		annotation SummarizationSetBy = Automatic

	column ultimate_parent_id
		dataType: string
		lineageTag: 51b51429-648c-4f81-91cc-9b21632071f0
		summarizeBy: none
		sourceColumn: ultimate_parent_id

		annotation SummarizationSetBy = Automatic

	column wikidata_ids
		dataType: string
		lineageTag: 07ce4f1c-1c1a-4282-9236-515f8896fb61
		summarizeBy: none
		sourceColumn: wikidata_ids

		annotation SummarizationSetBy = Automatic

	column wikipedia_url
		dataType: string
		lineageTag: cb878d42-3afb-4852-8746-ec1806cdf9a8
		summarizeBy: none
		sourceColumn: wikipedia_url

		annotation SummarizationSetBy = Automatic

	partition raw_research_organization = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    raw_research_organization_Sheet = Source{[Item="raw_research_organization",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_research_organization_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_dimensions_id", type text}, {"org_grid_id", type text}, {"org_name", type text}, {"acronyms", type text}, {"city_name", type text}, {"cnrs_ids", type text}, {"country_code", type text}, {"country_name", type text}, {"dimensions_url", type text}, {"established", Int64.Type}, {"external_ids_fundref", type text}, {"hesa_ids", Int64.Type}, {"hierarchy_details", type text}, {"isni_ids", type text}, {"latitude", type number}, {"linkout", type text}, {"longitude", type number}, {"nuts_level1_code", type text}, {"nuts_level1_name", type text}, {"nuts_level2_code", type text}, {"nuts_level2_name", type text}, {"nuts_level3_code", type text}, {"nuts_level3_name", type text}, {"organization_child_ids", type text}, {"organization_parent_ids", type text}, {"organization_related_ids", type text}, {"orgref_ids", type text}, {"redirect", type any}, {"ror_ids", type text}, {"state_name", type text}, {"status", type text}, {"types", type text}, {"ucas_ids", type text}, {"ukprn_ids", type text}, {"ultimate_parent_id", type text}, {"wikidata_ids", type text}, {"wikipedia_url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

