table raw_citing_clinical_trial
	lineageTag: 6bd77389-b160-49e4-8d41-0bea4eb5013a

	column cited_dimensions_id
		dataType: string
		lineageTag: f92ee724-b51a-4fe3-8fa4-a83cc53b6d72
		summarizeBy: none
		sourceColumn: cited_dimensions_id

		annotation SummarizationSetBy = Automatic

	column ct_id
		dataType: string
		lineageTag: 4ac21308-63a6-48ef-b9a4-c9a9400ad5ba
		summarizeBy: none
		sourceColumn: ct_id

		annotation SummarizationSetBy = Automatic

	column abstract
		dataType: string
		lineageTag: 63f5d7d5-d772-459f-b2c5-fdfc47e650ec
		summarizeBy: none
		sourceColumn: abstract

		annotation SummarizationSetBy = Automatic

	column acronym
		dataType: string
		lineageTag: 7512b424-8cef-48aa-b673-53ad447d9542
		summarizeBy: none
		sourceColumn: acronym

		annotation SummarizationSetBy = Automatic

	column active_years
		dataType: string
		lineageTag: 9df96954-8b7a-4453-a8ab-8bd245514f2c
		summarizeBy: none
		sourceColumn: active_years

		annotation SummarizationSetBy = Automatic

	column altmetric
		dataType: int64
		formatString: 0
		lineageTag: af9c67c2-5edc-4fe2-a7ba-94a3467b0e64
		summarizeBy: sum
		sourceColumn: altmetric

		annotation SummarizationSetBy = Automatic

	column associated_grant_ids
		dataType: string
		lineageTag: 7667bf2d-af80-4980-bba5-ef407520be1e
		summarizeBy: none
		sourceColumn: associated_grant_ids

		annotation SummarizationSetBy = Automatic

	column brief_title
		dataType: string
		lineageTag: f0af51af-bb16-4d9e-9cf5-ec698311c5bd
		summarizeBy: none
		sourceColumn: brief_title

		annotation SummarizationSetBy = Automatic

	column category_bra
		dataType: string
		lineageTag: 6d2d2be9-da98-47d6-b041-d3bc07942550
		summarizeBy: none
		sourceColumn: category_bra

		annotation SummarizationSetBy = Automatic

	column category_for
		dataType: string
		lineageTag: 2d8f8fd9-b3d9-4ff7-b01a-c70b158ccf5a
		summarizeBy: none
		sourceColumn: category_for

		annotation SummarizationSetBy = Automatic

	column category_hra
		dataType: string
		lineageTag: 3d5f6be8-f533-46d7-8a23-8ff34acb7035
		summarizeBy: none
		sourceColumn: category_hra

		annotation SummarizationSetBy = Automatic

	column category_hrcs_hc
		dataType: string
		lineageTag: db7fd05c-a9a7-4d0d-801f-22f0508b104e
		summarizeBy: none
		sourceColumn: category_hrcs_hc

		annotation SummarizationSetBy = Automatic

	column category_hrcs_rac
		dataType: string
		lineageTag: a515586b-e3b0-4188-8ed1-5a2a4d6953cd
		summarizeBy: none
		sourceColumn: category_hrcs_rac

		annotation SummarizationSetBy = Automatic

	column category_icrp_cso
		dataType: string
		lineageTag: c01d4a88-530f-4832-a148-85a6fe54d20c
		summarizeBy: none
		sourceColumn: category_icrp_cso

		annotation SummarizationSetBy = Automatic

	column category_icrp_ct
		dataType: string
		lineageTag: 85461a15-3db8-42eb-8545-265e2f533b1b
		summarizeBy: none
		sourceColumn: category_icrp_ct

		annotation SummarizationSetBy = Automatic

	column category_rcdc
		dataType: string
		lineageTag: e1e40d4f-5f6c-49b4-b269-751e209b69de
		summarizeBy: none
		sourceColumn: category_rcdc

		annotation SummarizationSetBy = Automatic

	column conditions
		dataType: string
		lineageTag: cd6a3141-c74f-44f2-baf7-1db93b1c59c2
		summarizeBy: none
		sourceColumn: conditions

		annotation SummarizationSetBy = Automatic

	column date_inserted
		dataType: dateTime
		formatString: Long Date
		lineageTag: 737072a7-bdeb-4b18-9d99-4f098f7e128b
		summarizeBy: none
		sourceColumn: date_inserted

		variation Variation
			isDefault
			relationship: 1f285e70-f2eb-4e37-90c9-d7cbc6ee2224
			defaultHierarchy: LocalDateTable_390bfcd1-b4ed-458c-9920-93bc5e267825.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dimensions_url
		dataType: string
		lineageTag: a2a62118-1350-40c1-93de-a4203637ea68
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 03819bdb-747a-406e-b532-b6cc9f6d7455
		summarizeBy: none
		sourceColumn: end_date

		variation Variation
			isDefault
			relationship: 60d7f3c6-9b83-4681-aacb-a985e6d85350
			defaultHierarchy: LocalDateTable_f24334dd-492f-4c88-a290-bf67d731369d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column funder_countries
		dataType: string
		lineageTag: 29752e49-439b-4c44-ab83-efb9b6b62301
		summarizeBy: none
		sourceColumn: funder_countries

		annotation SummarizationSetBy = Automatic

	column funders
		dataType: string
		lineageTag: fb154ee5-1a3e-4458-ac74-f79be90a222a
		summarizeBy: none
		sourceColumn: funders

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 49761e8e-aaa6-48e2-8e21-c546e88dd1c8
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column interventions
		dataType: string
		lineageTag: e97f39a2-a769-4165-a40b-dd5b8a3e0273
		summarizeBy: none
		sourceColumn: interventions

		annotation SummarizationSetBy = Automatic

	column investigators
		dataType: string
		lineageTag: 3424ea97-a1c4-4ab4-83dc-da2851d6cf67
		summarizeBy: none
		sourceColumn: investigators

		annotation SummarizationSetBy = Automatic

	column linkout
		dataType: string
		lineageTag: dcda7714-caef-4aac-892c-b11b18314b3a
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column mesh_terms
		dataType: string
		lineageTag: 202d1dd3-7634-453c-8888-2d5b70b81079
		summarizeBy: none
		sourceColumn: mesh_terms

		annotation SummarizationSetBy = Automatic

	column overall_status
		dataType: string
		lineageTag: 3670f2d1-45f5-4c95-a754-95711dcb1e7c
		summarizeBy: none
		sourceColumn: overall_status

		annotation SummarizationSetBy = Automatic

	column phase
		dataType: string
		lineageTag: 65296f6c-d6db-47cc-9c66-ab3d2a2edb34
		summarizeBy: none
		sourceColumn: phase

		annotation SummarizationSetBy = Automatic

	column publication_ids
		dataType: string
		lineageTag: 7954bd1b-af67-4ec9-b067-cc30052bad40
		summarizeBy: none
		sourceColumn: publication_ids

		annotation SummarizationSetBy = Automatic

	column registry
		dataType: string
		lineageTag: d9e21114-7a03-4851-ad3d-46c342f052d9
		summarizeBy: none
		sourceColumn: registry

		annotation SummarizationSetBy = Automatic

	column research_orgs
		dataType: string
		lineageTag: 02750ceb-4ad4-4354-86c1-6a1dc794e230
		summarizeBy: none
		sourceColumn: research_orgs

		annotation SummarizationSetBy = Automatic

	column researchers
		dataType: string
		lineageTag: 330e8e92-4bd5-411f-9178-68261c155dba
		summarizeBy: none
		sourceColumn: researchers

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c4897905-c372-4c87-b183-66cbf515afe6
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: a1b3b8d5-be0f-43d4-ae3b-0b2a06d9396a
			defaultHierarchy: LocalDateTable_75487b58-f010-4c17-8b04-3c47d2b82643.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column study_arms
		dataType: string
		lineageTag: eb0630f9-223c-40ab-9790-2a21d581167c
		summarizeBy: none
		sourceColumn: study_arms

		annotation SummarizationSetBy = Automatic

	column study_designs
		dataType: string
		lineageTag: ed935b52-4b85-4124-b91a-caa2ec95a3b2
		summarizeBy: none
		sourceColumn: study_designs

		annotation SummarizationSetBy = Automatic

	column study_eligibility_criteria
		dataType: string
		lineageTag: 3ec93754-02ad-43a1-9508-14b2dfc9a86c
		summarizeBy: none
		sourceColumn: study_eligibility_criteria

		annotation SummarizationSetBy = Automatic

	column study_maximum_age
		dataType: string
		lineageTag: b93a1254-d5d8-423c-af31-1ce472af8879
		summarizeBy: none
		sourceColumn: study_maximum_age

		annotation SummarizationSetBy = Automatic

	column study_minimum_age
		dataType: string
		lineageTag: 8f42ae33-5645-4e3b-a815-c43242798691
		summarizeBy: none
		sourceColumn: study_minimum_age

		annotation SummarizationSetBy = Automatic

	column study_outcome_measures
		dataType: string
		lineageTag: 33631eeb-572a-4104-80ac-99b4db2a3908
		summarizeBy: none
		sourceColumn: study_outcome_measures

		annotation SummarizationSetBy = Automatic

	column study_participants
		dataType: int64
		formatString: 0
		lineageTag: bbe841ea-d5af-4a30-9130-34553d812732
		summarizeBy: sum
		sourceColumn: study_participants

		annotation SummarizationSetBy = Automatic

	column study_type
		dataType: string
		lineageTag: a846bca1-3696-4b4c-b086-2c91c6869494
		summarizeBy: none
		sourceColumn: study_type

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 46fc4a5e-8879-4315-a229-c7736fab737b
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	partition raw_citing_clinical_trial = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    raw_citing_clinical_trial_Sheet = Source{[Item="raw_citing_clinical_trial",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(raw_citing_clinical_trial_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cited_dimensions_id", type text}, {"ct_id", type text}, {"abstract", type text}, {"acronym", type text}, {"active_years", type text}, {"altmetric", Int64.Type}, {"associated_grant_ids", type text}, {"brief_title", type text}, {"category_bra", type text}, {"category_for", type text}, {"category_hra", type text}, {"category_hrcs_hc", type text}, {"category_hrcs_rac", type text}, {"category_icrp_cso", type text}, {"category_icrp_ct", type text}, {"category_rcdc", type text}, {"conditions", type text}, {"date_inserted", type date}, {"dimensions_url", type text}, {"end_date", type date}, {"funder_countries", type text}, {"funders", type text}, {"gender", type text}, {"interventions", type text}, {"investigators", type text}, {"linkout", type text}, {"mesh_terms", type text}, {"overall_status", type text}, {"phase", type text}, {"publication_ids", type text}, {"registry", type text}, {"research_orgs", type text}, {"researchers", type text}, {"start_date", type date}, {"study_arms", type text}, {"study_designs", type text}, {"study_eligibility_criteria", type text}, {"study_maximum_age", type text}, {"study_minimum_age", type text}, {"study_outcome_measures", type text}, {"study_participants", Int64.Type}, {"study_type", type text}, {"title", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

