table sd_citing_organization_bridge
	lineageTag: 8cf39635-ae1e-4e57-99c8-fc250901bff9

	column Column1
		dataType: string
		lineageTag: 9c19a1fe-9adf-442e-9414-34186d513663
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 7e90ee95-3390-4fce-84f6-005c53d1f78f
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 53917121-dc4b-4be6-9bee-4bddff20025c
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: c6ea41b8-8399-4734-8839-a028192ec111
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: addf0958-87d4-46af-ae92-ae3127cfe0ba
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: e249347c-0c37-4550-abf6-38fed7f1ada2
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	partition sd_citing_organization_bridge = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    sd_citing_organization_bridge_Sheet = Source{[Item="sd_citing_organization_bridge",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(sd_citing_organization_bridge_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

