table sd_gsk_org_lookup
	lineageTag: 3b02fdd4-68a7-4d54-83fe-de6824162333

	column Column1
		dataType: string
		lineageTag: f7303388-69c0-4f22-9499-48ee951b51a2
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: e8036382-a3e8-4332-9f0f-68fe19384007
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: e4f7b8a9-c9a6-4e95-a1bb-aa29a9a2a175
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition sd_gsk_org_lookup = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    sd_gsk_org_lookup_Sheet = Source{[Item="sd_gsk_org_lookup",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(sd_gsk_org_lookup_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

