table sd_pub_citing_publication
	lineageTag: 258221ff-cf8a-40bd-bc73-21e94fe17009

	column citing_dimensions_id
		dataType: string
		lineageTag: f9b847ab-0eb7-4092-910e-67b34c1c4c2b
		summarizeBy: none
		sourceColumn: citing_dimensions_id

		annotation SummarizationSetBy = Automatic

	column citing_doi
		dataType: string
		lineageTag: 320cd602-4187-43a0-b51d-f4bfb901bed0
		summarizeBy: none
		sourceColumn: citing_doi

		annotation SummarizationSetBy = Automatic

	column journal_id
		dataType: string
		lineageTag: 870b7208-6e20-49ff-95ae-1bfed6fe9554
		summarizeBy: none
		sourceColumn: journal_id

		annotation SummarizationSetBy = Automatic

	column journal_title
		dataType: string
		lineageTag: 06a0fea0-21fc-4b49-9d9a-f9e746ce4d2f
		summarizeBy: none
		sourceColumn: journal_title

		annotation SummarizationSetBy = Automatic

	column pub_year
		dataType: int64
		formatString: 0
		lineageTag: d5dc9d09-e4e4-41ca-9734-7257df1ed52e
		summarizeBy: sum
		sourceColumn: pub_year

		annotation SummarizationSetBy = Automatic

	column times_cited
		dataType: int64
		formatString: 0
		lineageTag: a75c7d0f-da75-449f-865d-d56e7678d442
		summarizeBy: sum
		sourceColumn: times_cited

		annotation SummarizationSetBy = Automatic

	column field_citation_ratio
		dataType: string
		lineageTag: 6cdc1847-9efe-44fa-9fd1-7f6ef3787823
		summarizeBy: none
		sourceColumn: field_citation_ratio

		annotation SummarizationSetBy = Automatic

	column altmetric_score_citing
		dataType: string
		lineageTag: f41887a9-6225-480f-94e5-7aa05e9af1dc
		summarizeBy: none
		sourceColumn: altmetric_score_citing

		annotation SummarizationSetBy = Automatic

	partition sd_pub_citing_publication = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    sd_pub_citing_publication_Sheet = Source{[Item="sd_pub_citing_publication",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(sd_pub_citing_publication_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"citing_dimensions_id", type text}, {"citing_doi", type text}, {"journal_id", type text}, {"journal_title", type text}, {"pub_year", Int64.Type}, {"times_cited", Int64.Type}, {"field_citation_ratio", type any}, {"altmetric_score_citing", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

