table sd_research_organization
	lineageTag: 72fff270-1064-4402-83da-9fc8daed9ecc

	column source_dimensions_id
		dataType: string
		lineageTag: 86acf10e-6b62-4b43-860e-be503a8b8848
		summarizeBy: none
		sourceColumn: source_dimensions_id

		annotation SummarizationSetBy = Automatic

	column org_grid_id
		dataType: string
		lineageTag: 6beb2cec-dcac-45af-927a-dc1df48c2507
		summarizeBy: none
		sourceColumn: org_grid_id

		annotation SummarizationSetBy = Automatic

	column org_name
		dataType: string
		lineageTag: 1e0815cd-2945-413c-b865-c1939d9fc9df
		summarizeBy: none
		sourceColumn: org_name

		annotation SummarizationSetBy = Automatic

	column acronyms
		dataType: string
		lineageTag: 3f5150e4-2b64-4739-9072-f3409b026528
		summarizeBy: none
		sourceColumn: acronyms

		annotation SummarizationSetBy = Automatic

	column city_name
		dataType: string
		lineageTag: 3bee105b-4891-4833-a8e8-62bf1978efa1
		summarizeBy: none
		sourceColumn: city_name

		annotation SummarizationSetBy = Automatic

	column cnrs_ids
		dataType: string
		lineageTag: 1b3fe295-e231-4b4b-b9f7-f1472d56daa1
		summarizeBy: none
		sourceColumn: cnrs_ids

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: b894ceac-0381-47db-9575-bf4a2989bb59
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: 7befe91f-b8a7-45c6-b7fe-5a6f8ab7579d
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column dimensions_url
		dataType: string
		lineageTag: 2553798d-07ba-4ee6-9d86-50896523d944
		summarizeBy: none
		sourceColumn: dimensions_url

		annotation SummarizationSetBy = Automatic

	column established
		dataType: int64
		formatString: 0
		lineageTag: 9253a640-ce11-445e-840a-6944acce42bb
		summarizeBy: sum
		sourceColumn: established

		annotation SummarizationSetBy = Automatic

	column external_ids_fundref
		dataType: string
		lineageTag: 92deed37-866b-456a-8c84-203d30a323a5
		summarizeBy: none
		sourceColumn: external_ids_fundref

		annotation SummarizationSetBy = Automatic

	column hesa_ids
		dataType: int64
		formatString: 0
		lineageTag: bdfcfa40-9650-42c5-8541-3696bd96a11a
		summarizeBy: sum
		sourceColumn: hesa_ids

		annotation SummarizationSetBy = Automatic

	column hierarchy_details
		dataType: string
		lineageTag: 44a546f2-d980-4146-8826-9cd884b7eb85
		summarizeBy: none
		sourceColumn: hierarchy_details

		annotation SummarizationSetBy = Automatic

	column isni_ids
		dataType: string
		lineageTag: 3ee83c65-6585-4816-8910-5ded1cf281e9
		summarizeBy: none
		sourceColumn: isni_ids

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: cc6e8926-ce8f-4822-9a50-8c78c0fc80e1
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column linkout
		dataType: string
		lineageTag: b0f75ac0-efa6-4929-8343-8e90e30de8eb
		summarizeBy: none
		sourceColumn: linkout

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		lineageTag: 32c5966e-8710-40ef-b71a-498e710c3b1a
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nuts_level1_code
		dataType: string
		lineageTag: cd1a1fd7-258b-4a56-bdf9-b3c46493f304
		summarizeBy: none
		sourceColumn: nuts_level1_code

		annotation SummarizationSetBy = Automatic

	column nuts_level1_name
		dataType: string
		lineageTag: 8e0577df-bdfb-4d97-a2c3-e20eaf15e74d
		summarizeBy: none
		sourceColumn: nuts_level1_name

		annotation SummarizationSetBy = Automatic

	column nuts_level2_code
		dataType: string
		lineageTag: b042e3ac-1f57-4277-909d-c81ae6f876d6
		summarizeBy: none
		sourceColumn: nuts_level2_code

		annotation SummarizationSetBy = Automatic

	column nuts_level2_name
		dataType: string
		lineageTag: a002988a-2379-4602-805d-5d01d9ac8e79
		summarizeBy: none
		sourceColumn: nuts_level2_name

		annotation SummarizationSetBy = Automatic

	column nuts_level3_code
		dataType: string
		lineageTag: fd01549e-c2b3-4916-bbfe-68874f447075
		summarizeBy: none
		sourceColumn: nuts_level3_code

		annotation SummarizationSetBy = Automatic

	column nuts_level3_name
		dataType: string
		lineageTag: afb23dbb-4469-4831-ae48-c6661939961b
		summarizeBy: none
		sourceColumn: nuts_level3_name

		annotation SummarizationSetBy = Automatic

	column organization_child_ids
		dataType: string
		lineageTag: 56ee47dc-a771-41c1-88e8-2c6037f3bd0f
		summarizeBy: none
		sourceColumn: organization_child_ids

		annotation SummarizationSetBy = Automatic

	column organization_parent_ids
		dataType: string
		lineageTag: 5f6b0524-c116-4594-a4e1-e4cf1ed97fde
		summarizeBy: none
		sourceColumn: organization_parent_ids

		annotation SummarizationSetBy = Automatic

	column organization_related_ids
		dataType: string
		lineageTag: a4ae44b3-0fc5-494e-ba82-1a06ab01cb39
		summarizeBy: none
		sourceColumn: organization_related_ids

		annotation SummarizationSetBy = Automatic

	column orgref_ids
		dataType: string
		lineageTag: 482f4b43-bb92-4be1-ba21-240dc178c875
		summarizeBy: none
		sourceColumn: orgref_ids

		annotation SummarizationSetBy = Automatic

	column redirect
		dataType: string
		lineageTag: accdd470-71c8-45d4-9730-5cd252bfdb19
		summarizeBy: none
		sourceColumn: redirect

		annotation SummarizationSetBy = Automatic

	column ror_ids
		dataType: string
		lineageTag: ae9f0295-58b5-4b10-adb9-804be544ad67
		summarizeBy: none
		sourceColumn: ror_ids

		annotation SummarizationSetBy = Automatic

	column state_name
		dataType: string
		lineageTag: b7857bde-02ef-4264-ba4f-21a3afb1ee79
		summarizeBy: none
		sourceColumn: state_name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 1a700bc5-dcc6-42c9-9f5d-57b8899c21ac
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column types
		dataType: string
		lineageTag: 7b8bbaad-2d6b-4c5e-a535-1ad62e829461
		summarizeBy: none
		sourceColumn: types

		annotation SummarizationSetBy = Automatic

	column ucas_ids
		dataType: string
		lineageTag: 2fca4f1b-fbe8-4452-b8c0-70ef5706059c
		summarizeBy: none
		sourceColumn: ucas_ids

		annotation SummarizationSetBy = Automatic

	column ukprn_ids
		dataType: string
		lineageTag: 89ae6086-7f72-4d17-a781-77f062902b6d
		summarizeBy: none
		sourceColumn: ukprn_ids

		annotation SummarizationSetBy = Automatic

	column ultimate_parent_id
		dataType: string
		lineageTag: 18c05c24-c53f-47c9-8c18-154ecdeb4ea9
		summarizeBy: none
		sourceColumn: ultimate_parent_id

		annotation SummarizationSetBy = Automatic

	column wikidata_ids
		dataType: string
		lineageTag: 3067eb1d-a96a-4f90-a80d-5f84c049f76b
		summarizeBy: none
		sourceColumn: wikidata_ids

		annotation SummarizationSetBy = Automatic

	column wikipedia_url
		dataType: string
		lineageTag: 371bd173-2e94-4ade-b8c3-e61afb1036c6
		summarizeBy: none
		sourceColumn: wikipedia_url

		annotation SummarizationSetBy = Automatic

	partition sd_research_organization = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Nishant Dwivedi\Desktop\Downloads\impact_workbook (1).xlsx"), null, true),
				    sd_research_organization_Sheet = Source{[Item="sd_research_organization",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(sd_research_organization_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"source_dimensions_id", type text}, {"org_grid_id", type text}, {"org_name", type text}, {"acronyms", type text}, {"city_name", type text}, {"cnrs_ids", type text}, {"country_code", type text}, {"country_name", type text}, {"dimensions_url", type text}, {"established", Int64.Type}, {"external_ids_fundref", type text}, {"hesa_ids", Int64.Type}, {"hierarchy_details", type text}, {"isni_ids", type text}, {"latitude", type number}, {"linkout", type text}, {"longitude", type number}, {"nuts_level1_code", type text}, {"nuts_level1_name", type text}, {"nuts_level2_code", type text}, {"nuts_level2_name", type text}, {"nuts_level3_code", type text}, {"nuts_level3_name", type text}, {"organization_child_ids", type text}, {"organization_parent_ids", type text}, {"organization_related_ids", type text}, {"orgref_ids", type text}, {"redirect", type any}, {"ror_ids", type text}, {"state_name", type text}, {"status", type text}, {"types", type text}, {"ucas_ids", type text}, {"ukprn_ids", type text}, {"ultimate_parent_id", type text}, {"wikidata_ids", type text}, {"wikipedia_url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

